### ISSUE TITLE
Unify cancel handling

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1050]
We have currently two ways to propagate cancels in the code base.

1)  Method raise of zcx_abapgit_exception

https://github.com/larshp/abapGit/blob/7ffe82919d58fcebcb5a0c6d2d633c074f0423b1/src/zabapgit_zip.prog.abap#L100-L102

2) Raise exception zcx_abapgit_cancel 

https://github.com/larshp/abapGit/blob/7ffe82919d58fcebcb5a0c6d2d633c074f0423b1/src/zabapgit_services_git.prog.abap#L72-L74

Should we unify this? Which one is the preferred way to go?

**Comment by larshp** [comment]
Suggest using `zcx_abapgit_cancel`

**Comment by flaiker** [comment]
In general I don't think using exceptions for program flow control is a good idea at all. But in abapGit's case it's not worth it to refactor it, because so many standard function modules that are used are dialog coupled and throw the cancel-exception themselves (using the non-oo exceptions).

And just because I have the quote ready 🎃 

> A user tries to run the transaction on October 31 and an error is sent. This isn't 
> because of a problem with the program, but because all monsters refuse to work on 
> this day — in case they're mistaken for children dressed up as monsters and going 
> trick-or-treating, which would be the biggest humiliation that could happen to a 
> monster. 
> You still have to deal with these situations, but because you know for a fact they're 
> going to happen, dealing with such events is not exception handling. 

\- ABAP to the Future, Paul Hardy

**Comment by larshp** [comment]
think most of this is solved
