### ISSUE TITLE
Better handling of SAPUI5 (BSP objects)

### ISSUE THREAD

**Issue by kovboyjder** [larshp/abapGit#1076]
When you do  an import of an extract that contains existing UI5/BSP applications, you get an error, because it already exists, currently abapgit only supports creating new bsp's and not overwriting existing ones.
It's worth looking at http://yelcho.github.io/sapui5-deployer/ for inspiration.

**Comment by larshp** [comment]
What is the error message? 

Can you help creating a public repository which can help reproducing the issue? Suggest having 2 branches, one with version 1 and one with version 2, then updating the BSP can be simulated by switching to branch 2.

**Comment by larshp** [comment]
@kovboyjder see questions above

**Comment by 14r5** [comment]
Hi @larshp,
I had the same problem as @kovboyjder. On updating a WAPA application I only got an exception thrown at  ZABAPGIT_OBJECT_WAPA line 216. The comment in line 198 describes that this problem was also known to the programmer :)

To solve this issue I added the following statement in line 198:

>     IF me->lif_object~exists( ) EQ abap_true.
>       me->lif_object~delete( ).
>     ENDIF.
> 
Now it works very well.

Cheers,
Lars

**Comment by larshp** [comment]
@14r5 cool, feel free to submit the change as a pull request

**Comment by christianguenter2** [comment]
I think we can close this one?

**Comment by larshp** [comment]
yes
