### ISSUE TITLE
ZABAPGIT does not run in java gui

### ISSUE THREAD

**Issue by Boneill3** [larshp/abapGit#110]
I think that CL_GUI_HTML_VIEWER does not work on the java version of the gui and I am of course using a mac. This is what it looks like:
![screen shot 2015-08-27 at 4 52 08 pm](https://cloud.githubusercontent.com/assets/4459604/9536013/06e508ce-4cdc-11e5-8283-6cc3b0f318d4.png)

 I posted the issue to SCN at http://scn.sap.com/thread/3791232

I was thinking that an eclipse plugin could be a solution, but don't know if that will work without having a second install to split the single program in to separate classes.

**Comment by larshp** [comment]
hmm, will take a look, though I dont have a  JAVA sapgui available.

Could also look like the custom container is not being triggered

**Comment by larshp** [comment]
fixed, update to latest abapGit version and try again


I installed the java client on Windows and experienced the same error. The standard demo programs for html viewer worked okay(SAPHTML_DEMO1 + SAPHTML_EVENTS_DEMO + RSDEMO_HTML_VIEWER)

It turns out that java and webgui requires a screen to be present for it to show the container, fixed by adding a dummy selection screen. Also tried updating to rev 4 of SAPGUI Java did not fix the problem.

**Comment by Boneill3** [comment]
Confirmed resolved! Great work!
