### ISSUE TITLE
Syntax error in ABAPGit Plugin

### ISSUE THREAD

**Issue by A141117** [larshp/abapGit#1207]
We cloned ABAPGit Plugins repository from Github to SAP system ITX and got syntax error in the plugin classes “Type "ZIF_ABAPGIT_DEFINITIONS" is unknown “. Refer attached document.
[ABAPGit Plugin Issue.docx](https://github.com/larshp/abapGit/files/1730275/ABAPGit.Plugin.Issue.docx)

**Comment by larshp** [comment]
Hi,
Can you help adding the images directly in the issue instead of in a docx document?

Make sure to install the development version of abapGit, ie. all classes instead of the single report,
![image](https://user-images.githubusercontent.com/5888506/36297905-80d9a04a-12f5-11e8-88bb-5b7993cebccf.png)

**Comment by larshp** [comment]
tested ok here, no syntax errors, but there is a warning

**Comment by A141117** [comment]
Its resolved. Thank you.

**Comment by larshp** [comment]
👍 closing
