### ISSUE TITLE
Upgraded as per new SSL connection based on 22-Feb-2018- New branch issue

### ISSUE THREAD

**Issue by A141117** [larshp/abapGit#1232]
I have upgraded the SSL connection as per latets note released on 22-Feb-2018 and updated the abapgit code. I can do stage and commit but not able to create new branch in my test repository. Getting below error message after I enter the new branch name and press enter:

![image](https://user-images.githubusercontent.com/36180668/36770783-64c40936-1ca0-11e8-8519-27b514262d95.png)

**Comment by larshp** [comment]
is this related to the other issue you raised? see https://github.com/larshp/abapGit/issues/1230

please do not create multiple issues if they are related

**Comment by larshp** [comment]
Hi,
I somehow stumbled into the same issue. Problem is the local state of the repository, the error is not due to SSL or HTTP.

Workaround is to manually add the SHA1 of the latest commit,
![image](https://user-images.githubusercontent.com/5888506/38189131-f3694db8-365e-11e8-8f08-f5007e061e74.png)
previous value was "<SHA1/>" which is not expected.

I will open a PR which gives a better error message in a bit

**Comment by larshp** [comment]
closing
