### ISSUE TITLE
Feature Request: multiple packages per repository

### ISSUE THREAD

**Issue by Zeatynis** [larshp/abapGit#1237]
Hi,
would be great if I could create repo from chosen packages. Now I have to create multiple repos for one project and this is not fun.

**Comment by larshp** [comment]
hi, you can create one superpackage containing the packages needed in the repository

**Comment by Dave94** [comment]
Unfortunately I cannot. I've already defined package tree. I cannot modify it.

**Comment by larshp** [comment]
I think technically there are no restrictions to introduce or change a superpackage after package creation.

**Comment by Dave94** [comment]
Yes, it is possible but only if it won't blow up your entire company solutions 🤣 
If I could do it I would, trust me 😉

**Comment by Dave94** [comment]
I will give you an example:
Root
-->node1
---->node11
---->node12
. . .
---->node19
-->node2
---->node21
---->node22
. . .
---->node29

Let's say root is a package for some solutions and I have a project that uses node11 and node22 and also uses some node57 which is the new project.

**Comment by larshp** [comment]
yeah, perhaps we should consider adding it, everything just gets more difficult when there is a 1:n relation instead of 1:1(repo to package)

similar request: https://github.com/larshp/abapGit/issues/681

**Comment by esjewett** [comment]
I'd like to know more about this need. It sounds like an anti-pattern to me. The only reason I can think of that code would be in multiple packages with different super-package inheritance trees is if it is used (or intended to be used in the future) by multiple applications, like a library. But you generally would not want a library in your application repository, or if you do you want it there as a sub-module. Think what happens if one of these packages is being used in 2 different applications, each with its own ABAPGit repository. They are going to fight over ownership. It's not an intractable problem, but it seems like an unnecessary one.

Is this library-like approach what you are doing @Dave94, or is it something else?

**Comment by Dave94** [comment]
The case is that we have package with common subpackages for other projects. You know, packages with components that are used in many other projects. Now we have seperate repo for every component and for project package. Tracking changes is a bit annoying. But this is not the main problem. Main problem is that if we want to pull the project to another system we have to do it from every repo separately.

With ability to make repo with multiple packages we could have one repo for pulling to another systems.

**Comment by esjewett** [comment]
Yeah, but that's a job for a package & dependency management system. Trying to solve it by dumping everything in one repo (or in many many repos for the libraries) is just going to be a world of pain, IMO. The fact that ABAP doesn't have a package management system is a problem, but it didn't have a source control integration system until Lars wrote one either :D

**Comment by larshp** [comment]
abapGit will at some point be able to handle dependencies, eg. I have https://github.com/larshp/abapGitServer which requires https://github.com/larshp/ABAP-Swagger 

I'd like the above to be automatically suggested or handled somehow when installing a repo with depencencies

**Comment by esjewett** [comment]
So once it can do that you would want to keep all these packages in separate repos and then let abapGit install all the necessary packages when you install your application package? I assume? Seems like that is the solution to this problem, rather than multi-package repos. Though maybe there is a use-case there I'm not seeing. Anyway, didn't want to create a lot of work, but just do my usual and drive-by point out how the rest of the world does this ;-)

**Comment by larshp** [comment]
Guess this can be simulated by adding some code in the following user exit,
![image](https://user-images.githubusercontent.com/5888506/44190848-db9c0880-a128-11e8-810b-b8e1a9e06caf.png)

**Comment by jfilak** [comment]
I do understand that it would be a pain to remake the package hierarchy but I am all for fixing your package hierarchy than adding support to create a repo from a set of unrelated packages because that would:
- help you to continue using the sub-optimal package hierarchy
- help people to shoot themselves into the foot (I can picture the mess they could create)

**Comment by larshp** [comment]
out of scope, change the package hierarchy to reflect the git hierarchy

alternatively implement custom code in the user exit ZIF_ABAPGIT_EXIT~CHANGE_TADIR

closing

**Comment by habrahams** [comment]
Hi All,
I am aware that this can be simulated or implemented by implementing the exit, but this would still be a great feature for the following use case: Third party SAP solutions sometimes have to develop in different namespaces from an object perspective to form a complete solution in various packages(The various packages in the different namespaces can not be changed to form part of the same package hierarchy ). Thus you could end up with objects in a SAP namespace package PCXX, objects in a package with your company's namespace /xxxx/, and objects in the Z customer namespace package(e.g. infotypes as there exists no partner namespace or infotype number range). On this "layer" the packages combine as a software component(collection of packages) to make up the solution or add-on. SAP's SWC concept also bundles packages, as do third party add-ons that are certified by SAP. Thus with this in mind a software component(collection of packages) should logically relate to 1 repository for this use case.
Anyway, I would have loved to have this feature in abapGit, as I now have to solve this problem.

Regards,
