### ISSUE TITLE
Cannot clone enhacement implementation with enhancement spot

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1240]
If we define an enhancement spot in e.g. a program and implement it in the same repository, the repository cannot be cloned due to dependencies between them.

![image](https://user-images.githubusercontent.com/17437789/37146641-a197141e-22c4-11e8-9bd4-6d47515785aa.png)

Example repository.
https://gitlab.com/christianguenter/test_enhancement.git
![image](https://user-images.githubusercontent.com/17437789/37146627-9299a9c2-22c4-11e8-9337-aba6aa090dc8.png)

Solution would be to deserialize the spot before the implementation.

**Comment by jfilak** [comment]
When I clone an ENHO object (on my machine outside SAP GUI by copying the serialized file to a new one), I have to clean the element IMPL_SHORTTEXT_ID; otherwise I rewrite the original text id :)

**Comment by christianguenter2** [comment]
@jfilak is this an issue we should fix? Can you explain in a bit more detail how we can reproduce it? Maybe you would open a new issue then we can close this one?

**Comment by jfilak** [comment]
Well, I am not sure it is an issue you can fix. Here are the steps:
- create an ENHO object called FOO
- commit with abapGit
- pull the serialized file on your machine
- cp foo.enho.xml bar.enho.xml
- sed 's/foo/bar/' -i bar.enho.xml
- # few more changes through - vim bar.enho.xml 
- # here you must remove FOO's IMPL_SHORTTEXT_ID
- git add bar.enho.xml
- git commit
- git push
- abapgit pull

I do that because I sometimes need to copy an ENHO object and I am not sure how to do that in SAP.

**Comment by christianguenter2** [comment]
Which is your tool?
![image](https://user-images.githubusercontent.com/17437789/37531300-0ebac1d0-293c-11e8-9d90-b693b86b9730.png)

**Comment by jfilak** [comment]
BADI_IMPL

**Comment by christianguenter2** [comment]
I agree that's not something we can properly handle. Maybe generating the IMPL_SHORTTEXT_ID manually is another option. Of course there will be a chance conflicting with other existing IDs. I'll close the issue.
