### ISSUE TITLE
SAML: abapGit authentication question

### ISSUE THREAD

**Issue by qiankangMIT** [larshp/abapGit#1257]
Hi Lars,

After installing abapGit program zabapgit, we are facing an authentication issue. I am hoping you can provide some guidance as how to resolve this particular issue.

Our enterprise git  "https://github.mit.edu" does not use username/password but SAML to authenticate users. When https://github.mit.edu is called in normal use, a regular user would, first, be redirected to WAYF Service https://wayf.mit.edu. Upon choosing the account provider (which is MIT Kerberos account or MIT web certificate), the same user would then be directed, a second time, to MIT identity provide https://idp.mit.edu. At this point, the user can choose to use MIT certificate or Kerberos username/password to login to our enterprise github. 

The above presented a challenge. The abapgit program eventually discovers that auths are being requested for host https://github.mit.edu …and then eventually discovers that we’re missing something for authentication.  Eventually, the program displays the error “HTTP 403, forbidden”. 

So the question is how to incorporate SAML authentication into abapgit. Can you provide some guidance, suggestions, ideas? 

Any help will be much appreciated!

Best regards,
Qian Kang
qiankang@mit.edu

**Comment by qiankangMIT** [comment]
Hi Lars,

I think I should make my question more clearly. That is, how to pass authentication from abapgit program to SAML based enterprise github?

Thanks again!

Qian

**Comment by larshp** [comment]
uhh, SAML is a world of its own 😄 

I do not know how to implement this, there might be some SAP standard that can be used or set up.

Kerberos might also be difficult

hmm 😕 

Possible workarounds:
* Alternative means for auth on your GitHub Enterprise, like 2FA or personal access tokens, but I guess this cannot be done due to security policy
* use abapGit to export to zip, and use local PC git client to push to git
* use [abapGitServer](https://github.com/larshp/abapGitServer) instead of GitHub Enterprise, note that is features are limited. Depends on what scenarios you are planning to use abapGit for
* ?

**Comment by larshp** [comment]
@qiankangMIT any thoughts?

**Comment by larshp** [comment]
test

**Comment by larshp** [comment]
closing

for this to work out we need:
SAML login via http
Kerberos via http
which are both difficult(?), this has to be possible somehow, then we can integrate it into abapGit
