### ISSUE TITLE
Support for test data containers

### ISSUE THREAD

**Issue by antonioyanez** [larshp/abapGit#1263]
Hello Lars,

thank you very much for your tool! I have just installed it to keep maintain synchronize some local folders between different landscapes and it is working great.

Unfortunately, I have tried to push Test Data Containers, and they are ignored by abapgit (message: Object type ignored, not supported). Is it planned that they will be supported?

Cheers, Antonio

**Comment by larshp** [comment]
Hi,
I guess you are refering to ECTD objects? See https://github.com/larshp/abapGit/issues/105

Eventually they will be supported, someone just needs to write the code to handle it. Since this is a project driven by volunteers and interest, it is difficult to say when it will be added.

As always, pull requests welcome 😄

**Comment by larshp** [comment]
@antonioyanez can we close this issue and just have issue #105 open?

**Comment by larshp** [comment]
@antonioyanez can you help testing https://github.com/larshp/abapGit/pull/1287 ?

**Comment by antonioyanez** [comment]
Hello!

I will close this issue and test #1287. Thanks!
