### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by pokrakam** [larshp/abapGit#1285]
Not sure if I'm missing something but tracing errors is difficult. There's just a message without even being able to get hold of the message ID/Number (so we can't set a message breakpoint in order to debug). It would be nice to have a better idea of failures when things go wrong.

At present someone who is not familiar with the code can spend a long time debugging - e.g. I'm currently facing RS_CUA_INTERNAL_WRITE (no idea if it's related to #831) during a new import of a repo, and I have no idea which object is even causing the issue. So this is making it more difficult for people to help fix stuff :-(

Thus my suggestion: have a central message handler that can be stopped - perhaps using an activatable checkpoint - and/or as a quick hack provide some more runtime info. This is not a high priority, and I may have a look into this myself when I have some time, but I thought I'd record the idea here anyway.

**Comment by larshp** [comment]
Hi Mike,
typically messages are raised with ZCX_ABAPGIT_EXCEPTION, try setting a breakpoint in method

https://github.com/larshp/abapGit/blob/master/src/zcx_abapgit_exception.clas.abap#L74-L80

we cannot use real message ID and numbers or checkpoint groups due to the way abapGit is distributed. Perhaps we can do an evil hack somehow, store messages and IDs in an internal table.

**Comment by FreHu** [comment]
I just found out about this button, you can use it to get to the line where a message was raised:

https://blogs.sap.com/2018/07/05/new-tool-to-get-to-the-place-where-an-abap-message-was-raised/

**Comment by larshp** [comment]
think this was solved with the new error handling/exception setup, closing
