### ISSUE TITLE
Syntax Error in ZCL_ABAPGIT_SERVICES_GIT: "IS_WRITE_PROTECTED" is unknown

### ISSUE THREAD

**Issue by patvo** [larshp/abapGit#1302]
Hi.
Recently updated from 1.59.0 to 1.63.0. 
Now I’m getting a syntax error in ZCL_ABAPGIT_SERVICES_GIT when trying to switch branches or pull (haven’t done any further testing yet): ‘Method "IS_WRITE_PROTECTED" is unknown or PROTECTED or PRIVATE.’
[SYNTAX_ERROR-ZCL_ABAPGIT_SERVICES_GIT.txt](https://github.com/larshp/abapGit/files/1886609/SYNTAX_ERROR-ZCL_ABAPGIT_SERVICES_GIT.txt)

**Comment by flaiker** [comment]
Does the class show up as changed on remote in abapGit? And if you pull that does not change?

Can you try to overwrite the class ZCL_ABAPGIT_SERVICES_GIT manually using the version in [master](https://github.com/larshp/abapGit/blob/master/src/ui/zcl_abapgit_services_git.clas.abap)?
The method in question has been removed and refactored in f17985b27e596958fa110dbad24b29fae59f841f.

There seem to be some problems recently when pulling new versions of a class and only parts being updated (maybe since the new class deserialization is active?).
