### ISSUE TITLE
ITAB_DUPLICATE_KEY

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1482]
Follow up on #1477 

Steps to reproduce:

1) create a package with a class and commit
![image](https://user-images.githubusercontent.com/17437789/41200453-04d254ec-6ca5-11e8-9e42-e11811a99a23.png)

2) create a subpackage, move the class to the subpackage and commit to a new branch
![image](https://user-images.githubusercontent.com/17437789/41200467-2e3a28fa-6ca5-11e8-940d-53bace1615d0.png)

3) switch back to the first branch as no pull is possible do 'reset local'
![image](https://user-images.githubusercontent.com/17437789/41200485-5f69c200-6ca5-11e8-8d58-2511dbec4e14.png)

**Comment by larshp** [comment]
can this be reproduced with less manual steps? 

I guess "1" and "2" can be created as examples in a public repo?

**Comment by christianguenter2** [comment]
Yes. 

1) Clone this [repo](https://gitlab.com/christianguenter/test_move_package.git) branch new_package.
2) switch to master -> 'reset local'

**Comment by gregorwolf** [comment]
Some time ago I've cloned  https://github.com/Microsoft/ABAP-SDK-for-Azure.  Today I've tried to update and got the error "A row already exists with this key".  I've made abapGit working by skipping the line:

```lt_items_idx = lt_items.```

in the debugger. I've did a abapGit update and cloned the Microsoft repository again. Until now no issues.

**Comment by hardyp** [comment]
I got the error by starting a "pull" of a repository in one session, and whilst that was importing objects, open another session and then call the ZABAPGIT transaction. Both sessions dumped, and thereafter I could not start ZABAPGIT without a dump.
In the internal table LT_ITEMS there were two lines for every object type / object combination, one with a development class, one without. Since LT_ITEMS_IDX needs a unique combination of object type / object a dump occurs. 
I could solve the symptom by sorting LT_ITEMS and losing the entries without the development class, but I suppose that is just papering over the cracks.

**Comment by larshp** [comment]
Looks like a caching problem, the class is deleted via the following popup,
![image](https://user-images.githubusercontent.com/5888506/41506107-9f6d363a-7217-11e8-8b85-34365a9d0eab.png)
but in the status calculation it still think it exists locally

**Comment by christianguenter2** [comment]
Issue is fixed. Thanks @larshp
