### ISSUE TITLE
Advanced -> Uninstall leaves lock

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1512]
Steps to reproduce:
a: install repo
b: Select Advanced -> Uninstall
c: do not exit the screen
d: Check SM12 in another session

Looks like a commit is missing somewhere

**Comment by christianguenter2** [comment]
This is caused by method TOGGLE_FAVORITE in  ZCL_ABAPGIT_PERSISTENCE_USER and also occurs when toggling favorites. After UPDATE the commit is missing. 
The other TOGGLE* methods also don't have a commit, probably we should change them too.
https://github.com/larshp/abapGit/blob/66b91e45a934ba9f4745a85392be25c7514d37a9/src/persist/zcl_abapgit_persistence_user.clas.abap#L492-L509
