### ISSUE TITLE
Plugin-mechanism vs. single file shipment

### ISSUE THREAD

**Issue by mrsimpson** [larshp/abapGit#164]
As far as I can see ABAPGit holds all the features for the supported object types in a single report.
In contrast to that, SAPLink provides a dynamic loading of new components.
Benefit of the all-in-one-approach of course is that there's no bootstrapping issue as well as less runtime-errors due to plug-ins implementing e. g. an obsolete interface.
However, this slows down development, I'd guess. Any idea how to find a compromise?

**Comment by gregorwolf** [comment]
For SAPlink the Report [ZSAPLINK_STEAMROLLER](https://www.assembla.com/spaces/saplink/subversion/source/HEAD/trunk/installer/PROG_ZSAPLINK_STEAMROLLER.slnk) was created. It creates the ZSAPLINK_INSTALLER report by transforming the global classes into locals. So it is a build process for ABAP. Perhaps this could be reused here. Thoughts?

**Comment by mrsimpson** [comment]
same thought here ;)

**Comment by VishnAndr** [comment]
Personally I use an own include in main program for development or adjustments. And when the process is finished and new object is fully supported I just transfer new local classes from this include to main program.

**Comment by larshp** [comment]
One of the main goals is to have an easy installation/upgrade of the program, but lately I've been getting worried because it takes longer and longer to copy/paste the code into the system.

For issue #75 I've added the following code in the main program(gateway is also a bit special, not sure how to handle it in a nice way yet),
https://github.com/larshp/abapGit/blob/master/zabapgit.abap#L3155
we can add more for ease of development? In case you are adding support for more object types?

The idea with steamroller is good, but it also introduces complexity, contributing a change to abapGit right now can be done directly in the github web interface without any tools. Looking at the history of abapGit there have been a total of 8 pull requests in total, so its not a large problem yet, though it seems like its picking up.

**Comment by RainerWinkler** [comment]
@gregorwolf thanks for mentioning ZSAPLINK_STEAMROLLER. Sounds interesting. I face the same problems. Developing with separate global classes is simple, but a single program is easier to be moved. This is vital for a tool like a model extractor, that will probably of much value during trouble shooting. 
But I do not think, that abapGit is a tool, that will be implemented into a system just by doing copy and paste of a single report. So I think implementing abapGit with a couple of classes and reports would also be fine.

**Comment by mrsimpson** [comment]
I believe it might be an idea to reduce the number of artifacts to a minimum. At least the interface and some implementing superclasses should be global. This would enable proper development of separate plugins (no include with local classes). The essential parts could be built using steamroller.
Though the dynamic determination of plug-ins in saplink is nice, I'd favor to have them referred to (as strings) in the main program. That would make it possible to understand the progress of the supported objecttypes while reducing the footprint.

**Comment by larshp** [comment]
Hmm, think this is going in a lot of different directions :smile: 

### Development slow down
@mrsimpson are you working on support for another object type? Will adding a INCLUDE IF FOUND work for your immediate requirement? And when done copy it into the main program. Looking at the 2 year history of abapGit there have been a total of 6 external pull requests, so I dont currently see this as a large problem. I've lately been doing quite a few commits https://github.com/larshp/abapGit/graphs/commit-activity which might force you to update the program you are working on, but things will probably slow down again.

### Installation is slow
It takes 110 seconds to copy the code into SE38 using the old editor, and 2 seconds in the new editor. So this is probably okay.

### Steamroller
I'm not quite there yet. abapGit might be a mess to develop in one single file, but it makes the installation very easy for end users. Introducing a build system and multiple files to download/install makes it more difficult for end users and contributors. Applications distributed via abapGit can be developed in the correct/nice way, some bad code has to be created to bootstrap programs like abapGit.

On the other side, I could imagine a ZABAPGIT_INSTALLER where a zip file is imported by the user. The installer would install objects in a separate package, keep track of which version is currently installed, which will allow transparency as to what is installed. Plus allow for update and uninstall features of abapGit.

@RainerWinkler if you choose to distribute your model extractor via SAPLINK or abapGit you wont have to worry about installation/distribution.

The current approach is very simple(perhaps too simple) and transparent, which I think will encourage more people to try out the project, plus encourage more people to contribute.

**Comment by larshp** [comment]
In the suggestion above the installer ends up having to implement many of the same features as the installed program.

@mrsimpson submitted a pull request yesterday(https://github.com/larshp/abapGit/pull/167) with some interesting stuff for the plugin approach, instead of steamrolling into an installer, then allow a way out of of the main report to call plugins.

I've taken some of the ideas and put into a bit of code see https://github.com/larshp/abapGit-Plugins. The installation approach will be to first install zabapgit.abap as normal from the normal repository, and afterwards use zabapgit itself to install the plugins from a different repository containing the plugins.

Some abapGit objects are serialized into multiple files, so the file container class has been added for allowing this. Support for new object types would have to implement interface ZIF_ABAPGIT_PLUGIN and inherit from ZCL_ABAPGIT_OBJECT. Its far from done, but it outlines an approach, comments/concerns/suggestions welcome.

The bits in https://github.com/larshp/abapGit-Plugins/blob/master/zabapgit_addition.txt will have to go into the main program. Adding the code in an INCLUDE IF FOUND, I'm afraid that if there sometime in the future are large refactorings in zabapgit, then it will end up having syntax error in the main program due to the includes. Everything is also dynamically referenced so the main program will work without installing the plugins.

I'd still like as much as possible to go into the main program, but plugins are needed to support some of the objects introduced after 702 like Gateway + BOPF + FPM(?). The alternative is to have a big mess of dynamic references.

**Comment by mrsimpson** [comment]
Isolating the plugin-interface from the object type classes in the core sounds reasonable to me. I don't expect plugins to be updated regularly, so having a superclass which might even implement (tag-) interfaces so that ABAPGit can handle (in theory ;) ) multiple plugin-versions makes good sense.
In every case, this is a much better contract than INCLUDE... IF FOUND.

**Comment by mrsimpson** [comment]
One tricky part of course is how to enable access to the local implementations in the program without copying all the code. I forked the plugins-repo and might try some things beginning of next week.
But a a first glance, with respect to the contract it feels nice.

**Comment by larshp** [comment]
yes, could do PERFORM IN, as mentioned in
https://github.com/larshp/abapGit-Plugins/blob/master/zcl_abapgit_file_container.clas.abap#L36
or do some tricks like this:
https://github.com/larshp/abapCov/blob/master/zabapcov.prog.abap#L458
though not sure how it will work out

lets give the other guys a few days to come forward with comments and concerns, if they are interested. If nothing new comes up, I think we should just try to move forward to see where it goes :smile:

**Comment by mrsimpson** [comment]
I don't want to rush anyone here, I just could not resist coding ;)

## POC
I have implemented a working version based on your interface. You can check it in https://github.com/mrsimpson/abapGit/tree/plugin-enabling. Some plugins are implemented in https://github.com/mrsimpson/abapGit-Plugins . 
I have opted for exposing the local classes implementations by proxy-ing them with a global class.
from an API-perspective, this feels good for me and the effort o keeping those implementations in sync is limited. I basically means that possible interface-changes need to be done redundantly.
In my implementation, I injected a factory for the locals into the superclass. The superclass then acts as factory for the xml-helper-class. 
What I don't like about that current implementation is that the constructor's interface had to be enhanced. Most likely, `'\PROGRAM=ABAPGIT\CLASS=LCL_HELPER_FACTORY'=>CREATE` will do a better job, I didn't know about that option.

## Plug-Mechanism consumption
API and general implementation feels good for me. It feels a bit awkward that the actual plugin-implementation needs to implement the plugin-interface (and not the superclass), but this way, it's obvious what the plugin-developer needs to implement.

## Installation
I can imagine the following process:
* Copy the ZABPGIT
* from the menu, offer an feature which clones an ABAPGIT-repository and updates the program to it's full capabilities (e. g. installing built-in-object-support-classes)
* provide an option to install plugins from multiple resources (could e. g. be done by providing a particular link-file in the ABAPGit-repository). Also here, cloning a repository would be a nice option du to potential un-installation-ease.

This way, only a limited set of classes would need to be available as locals. The rest could be cloned.
Could I express my idea?

Cheers, 
Oliver

**Comment by larshp** [comment]
ABAP is fun :stuck_out_tongue: 

1. https://github.com/mrsimpson/abapGit/tree/plugin-enabling can you refork it to the current master branch? The copyrighted code is still in the git history. Plus there are 2 abapgit files .abap and .prog.abap, the .prog.xml file is not needed.

2. How much work do you think it would be to rewrite the generic adapter to use https://github.com/mrsimpson/abapGit-Plugins/blob/master/zcl_abapgit_xml_proxy.clas.abap ? If that can be done then I guess we dont need any saplink stuff?

**Comment by mrsimpson** [comment]
Of course ABAP is fun. 
1. I don't get the Git-terminology, sorry. Which files would you like me to remove and what shall I do with the branch? Integrate it where?

2. You mean re-writing https://github.com/mrsimpson/SAPLink-Plugins/blob/master/zsaplink_generic_obj.clas.abap
* just that it inherits from the zcl_abapgit_object?
* uses the add_table of the xml-helper natively?

I don't like the thought of maintaining two plugins, but the effort is not too huge.

**Comment by mrsimpson** [comment]
Apart from the generic sink-based plugin (which is actually nothing more than a workaround for missing APIs), there are a couple of saplink-plugins I use (e. g. Webdynpro configurations). 
Of course, one could copy all of them but I don't think this is the proper approach with respect to maintainability. Better get that licensing aligned. Afaik Saplink has moved to Apache License some time back. Would that not be an option as well?

**Comment by larshp** [comment]
1. The GPL objects are part of the git history in https://github.com/mrsimpson/abapGit/commits/master , so this cannot be merged due to the copyrights. The easiest way to solve this is to delete the fork/repository in github(goto settings, make sure to backup), and fork again.

2. oh, think I understand the "multiple sources" comment now, the installation would be
a. install zabapgit via copy paste
b. install https://github.com/mrsimpson/abapGit-Plugins using abapgit
c. install https://github.com/mrsimpson/SAPLink-Plugins using abapgit

If the generic object handler is rewritten then there is no worry about licenses and step c) could be skipped, and perhaps even merge the code into a) in the future. This is off cause something you need to decide.

I think it is important to keep the installation as easy as possible. For SAPLink(which is a great product) I've seen a lot of issues where users have had trouble installing the plugins or did not install the plugins at all, i.e. more installation steps more end user issues.

**Comment by larshp** [comment]
yuck, licensing

Changing license raises a lot of questions. I'm not very familiar with the Apache License, so I don't know if it is possible, and what the consequences, are if any.

I think it is important to keep a tool for distributing code as permissive as possible, that's why I originally chose the MIT license.

Originally when starting out this project I wanted it to move in a different direction than SAPLink(which is a great product), see design goals in README.md. It will require a lot of effort to move in that direction, but I think it will benefit the community as a whole and open for new possibilities.

**Comment by larshp** [comment]
Though, that being said, I'm okay with accepting the code that's in https://github.com/mrsimpson/abapGit-Plugins and the necessary changes to zabapgit.abap :smile:

**Comment by mrsimpson** [comment]
## Implementation
Changed the implementation with respect to the proxies and their instantiation. Calling the local class dynamically (via \PROGRAM=ZABAPGIT\CLASS=LCL...) makes the injected io_helper_factory unnecessary. Instead, the proxies themselves and the plugin-superclass now take responsibility for proper instantiation and consumption. This feels much better and doesn't affect the plugin-constructor-interface anymore. Technically, I'm happy with this solution.

## Backporting
Re-forked again and added the report. Nothing more. See https://github.com/mrsimpson/abapGit/tree/plugin-enabling
I was about to submit a pull-request, but I'm not sure what should be part of the abapGit Repository.
* The Git-ed ZABAPGIT (.prog.xml and .prog.xml). I like to have this in the repo as it allows me to easily work on the report.
* [Additional ABAPGit-Report source (.prog)](https://github.com/mrsimpson/abapGit/blob/plugin-enabling/zabapgit.abap): This on the other hand is redundant. I also don't see a benefit compared to zabapgit.prog.abap. One could also copy-paste from there.
* The artifacts enabling plugins (not the plugins themselves, but the global interface, superclass, proxy-classes) are not technically needed in order to run ZABAPGIT, but logically they belong there. I'd like them to be included as adoption to ZABAPGIT might affect them being changed as well.

Thoughts?

**Comment by larshp** [comment]
I recommend using the github web interface or your favorite git client to update zabapgit.abap, uploading changes for abapgit via abapgit is easy, but downloading changes for abapgit via abapgit is not possible as it would overwrite the running program. 

So to avoid confusion I think we should keep the file that is there and not add additional files. Also currently it is difficult to tell what has changed between
https://github.com/mrsimpson/abapGit/blob/plugin-enabling/zabapgit.abap
and
https://github.com/mrsimpson/abapGit/blob/plugin-enabling/zabapgit.prog.abap
when looking at the commit history, it would require to download both files and compare via diff tool.

**Comment by mrsimpson** [comment]
Agreed: Keeping both is nonsense.
However, I didn't expect and don't experience issues updating ZABAPGIT via ZABAPGIT : I could easily pull the object from the repo, it got compiled and the load changed on next program execution.
How did you manage to get problems?

**Comment by larshp** [comment]
Problems: just an assumption, never actually tried it. Interesting, lets keep it as is for now, we can investigate later if it can be done.

Empty diff: There is sometimes a troublesome newline as the last character in the files. Not sure where it breaks, another bug to be fixed

**Comment by mrsimpson** [comment]
Feel free to copy the code from https://github.com/mrsimpson/abapGit/blob/plugin-enabling/zabapgit.prog.abap to your master https://github.com/larshp/abapGit/blob/master/zabapgit.abap.
I will continue with my branch and gather some more experience, if this is ok for you.

**Comment by larshp** [comment]
There is no hurry, when you think its okay, just submit a pull request, then you'll also get your name on the contributors list. If we later find out something is missing/should be done in another way, just submit a new pull request, I'm all for many small incremental changes and getting the code out there. :shipit:

Few minor issues:
a. ZCX_ABAPGIT_OBJECT is not known when installing the main program, plus it should work on 702, so replace
```abap
CATCH zcx_abapgit_object INTO DATA(lx_plugin).
```
with
```abap
CATCH cx_static_check INTO lx_plugin.
```

b. the exception is caught by the GUI layer, tested it and it seems to work okay
```abap
_raise lv_message. "todo: Currently this exception stops program execution
```

c. another 740 construct,
```abap
io_xml        = CAST #( io_xml )
```
