### ISSUE TITLE
Run code inspector in parallel

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#1774]
Set `P_HOWTORUN = 'L'`, then CI will run in parallel.

However currently the inspections are not persisted, this is required for it to be able to run in parallel.

Solution: persist, run, and delete after retrieving the results

![image](https://user-images.githubusercontent.com/5888506/43714466-5de8c750-997d-11e8-89e7-cf645f80094f.png)

**Comment by christianguenter2** [comment]
I implemented this and did some measurements on my machine (NW752 SP01, VirtualBox, 2 processors, 6 GB RAM). 
https://github.com/christianguenter2/abapGit/tree/1774

I tested with the abapGit repo itself and tried
a) Syntax check
b) Code inspection with syntax check, extended program checks and ABAP unit tests

Testcase | Serial | Parallel 2 dialog WPs  | Parallel 10 dialog WPs
---------|----------|---------|------
a | 11.5 | 30 | 6
b | 15 | 50 | 8

With 2 dialog WPs there wasn't a parallelization at all. With 10 dialog WPs the code inspection was distributed to 7 WPs.

My conclusion is that there's a significant performance decrease with enabled parallelization on systems with few (free) dialog process. With abundant work processes there's roughly a 50% performance increase. Which is quite ok, but not as huge as one would expect. 

But my measurements are neither representive nor scientific. They only give a rough indication. Maybe I did something wrong and the result mays vary tremendously in other setups.

I think we have four options now
1) Don't consider parallelization at all
2) Enable parallelization by default
3) Enable parallelization by user setting, disabled by default
4) dynamically detect whether there are more than, let's say 5, free dialog work processes and then parallelize, otherwise not.

Any opinions?
