### ISSUE TITLE
Dump CX_SY_RANGE_OUT_OF_BOUNDS in  ZCL_ABAPGIT_SYNTAX_HIGHLIGHTER

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#1799]
Steps to reproduce:

1) clone [demo](https://gitlab.com/christianguenter/test_diff_rendering.git)
2) click on view diff near file /src/z_test.wapa.fragment.xml

![image](https://user-images.githubusercontent.com/17437789/43795337-54b98660-9a81-11e8-90b7-b3c4290195fd.png)

![image](https://user-images.githubusercontent.com/17437789/43795205-ef37f7cc-9a80-11e8-980a-4a07c1eef204.png)
![image](https://user-images.githubusercontent.com/17437789/43795219-f7898ce2-9a80-11e8-805a-265b3f3cf160.png)
![image](https://user-images.githubusercontent.com/17437789/43795227-005dd9ae-9a81-11e8-89da-7be5dcd64a7c.png)

![image](https://user-images.githubusercontent.com/17437789/43795260-18589d5a-9a81-11e8-9e87-e19a52fd720d.png)

**Comment by christianguenter2** [comment]
Line contains 
`text="{i18n>Menu}"  `
it seems that the > is the root cause.

**Comment by christianguenter2** [comment]
It seems that this regex for xml tags isn't sufficient.
https://github.com/larshp/abapGit/blob/26c6f4b4dc9db279c905146bb781cc9f9be89740/src/syntax/zcl_abapgit_syntax_xml.clas.abap#L22

**Comment by marcellourbani** [comment]
had a quick look but I get an empty sintax check page.
Perhaps I need to set up a default code inspector variant or something?

**Comment by christianguenter2** [comment]
It has nothing to do with syntax check page or code inspector. Just open the diff of z_test_wapa.fragment.xml.

**Comment by marcellourbani** [comment]
Dumps. I will pick this up if you're not working on it already

**Comment by christianguenter2** [comment]
Cool, I'm not working on it.

**Comment by marcellourbani** [comment]
It's not as simple as changing a regex

First of all, our regexes are without submatches, so if I try to escape away 
(?:"(?:(?:[^"]|(?:\\.))*)")?([<>])
would actually work, and return the first submatch as < or >

I will extend the engine to support submatches, which will remove the dump

If we also want to properly highlight the tags we would need to remember we left one opened the line above.

Will look into it and add that too, otherwise we'll end up with something like this:

![image](https://user-images.githubusercontent.com/2453277/45534421-f7abcc00-b7f2-11e8-80f5-a4c9f1fe61f0.png)

**Comment by marcellourbani** [comment]
ok, that was a much smaller issue, works now:
![image](https://user-images.githubusercontent.com/2453277/45540545-a60c3d00-b804-11e8-8a83-8ab1ff9584e5.png)
did have to use submatches
