### ISSUE TITLE
Auto-generated header

### ISSUE THREAD

**Issue by patvo** [larshp/abapGit#1811]
Hi there.
I would like to suggest a new feature: an optional auto-generated header comment block with all the information from the commit.

Maybe with a little checkbox at the commit dialog to select, (where possible) which files should get an auto-generated header?

What do you think? 😃 

Something like this:
```
*&---------------------------------------------------------------------*
*& Auto-generated by abapGit: <filename>								   *
*&---------------------------------------------------------------------*
*& DATE:		<date>, <time>
*& COMMIT ID:		<commit id>
*& COMMITTER:		<name>, <committer e-mail>
*& COMMENT:		<comment>
*& BODY:		<body>
*&			<body>
*&			<body>
*&			<body>
*& AUTHOR:		<name>, <author e-mail>
*&---------------------------------------------------------------------*
*& DATE:		<date>, <time>
*& COMMIT ID:		<commit id>
*& COMMITTER:		<name>, <committer e-mail>
*& COMMENT:		<comment>
*& BODY:		<body>
*&			<body>
*&			<body>
*&			<body>
*& AUTHOR:		<name>, <author e-mail>
*&---------------------------------------------------------------------*
```

**Comment by patvo** [comment]
@larshp 
Hi!
I do not see this related to the background mode.
An auto-generated comment block only makes sense if there is a useful commit message. 
AFAIK, reading the body of a commit message requires a third party tool at the moment. That is the reason why I am mostly leaving the message body blank. >.<
Being able to auto-generate the stated commit message (the body) into the code would make more use of the commit dialog. 
Besides, it would be a nice feature to see the comments of the last changes on top of the ABAP code.

**Comment by flaiker** [comment]
I don't like it. Isn't one of the main features of a version control system to not store "version information" in the code to make it more readable? You also might want to intentionally separate these so that in product development the customer doesn't get all your internal development information delivered as well.

I saw some classes in the wild which have generated version comments from the associated transports in each method implementation. Which leads to having huge classes that mostly consist of comments.

Also think of merge conflicts on the generated comments / branching / much additional noise in the git history.

So yea, personally not a fan of the idea.

What I maybe would like to see is a generated header in each source file that only shows up when browsing in the file system but gets removed on the abap side, which contains maybe a link to the project and copyright information or something.

**Comment by larshp** [comment]
I agree with @flaiker the information is in git, replicating is more work.

In ABAP we have quite bad tools, and currently it is difficult to connect the code being edited with the git version history. Ideally this should be integrated into the IDE, which is Eclipse, so I suggest adding this as a feature in https://github.com/abapGit/ADT_Frontend

**Comment by patvo** [comment]
Thanks for the answers!

@flaiker
I get your point, avoiding redundancy and unreadable code. 

> What I maybe would like to see is a generated header in each source file that only shows up when browsing in the file system but gets removed on the abap side, which contains maybe a link to the project and copyright information or something.

That would be nice too.

@larshp 
Would it be much of hassle to get the commit message body shown (e.g. as a hoverbox) in the branch overview?

**Comment by larshp** [comment]
@patvo no, suggest opening a new issue for showing the body in the branch overview screen

**Comment by patvo** [comment]
@larshp Thanks, I'll do that.
