### ISSUE TITLE
Staging: warning if there is an inactive version

### ISSUE THREAD

**Issue by bigld** [larshp/abapGit#1943]
in the object list there should be an indicator for inactive objects
also a warning message when staging files

**Comment by larshp** [comment]
yeah, any thoughts on how to implement?

**Comment by bigld** [comment]
not yet - just as reminder
I will do some research and come up with a proposal

**Comment by marcellourbani** [comment]
I would just forbid to stage if inactive.
Also because some serializer might pick the active version, some the inactive one.
TMS uses FM RS_INACTIVE_OBJECTS_WARNING 
![image](https://user-images.githubusercontent.com/2453277/45917626-9e870c80-be72-11e8-875a-871c85c09a2a.png)
...which doesn't seem to care about TRKORR at all.
I would just feed it a fake e071 with the current object and see what it returns.
Wouldn't use a table with multiple objects as the inactive part might be different from the whole object: that's what I get for PROG ZTESTMU2
![image](https://user-images.githubusercontent.com/2453277/45917712-8d8acb00-be73-11e8-8f57-477297125fd7.png)

**Comment by bigld** [comment]
@marcellourbani: thanks, that's the FM I was thinking about.
But I wouldn't reject staging with inactive objects. When the active version wasn't commited so far, one can do this and then activate and commit the changes

**Comment by marcellourbani** [comment]
Are you 100% sure waht you commit is what you see in eclipse/se80, for all
object types when they're not active?And that it will be true for objects
added tomorrow/third part plugins?
I', not.

**Comment by bigld** [comment]
One can check all diffs in the staging screen and even stage patches and this is what will be commited.
If there is a warning on inactive objects, I will have a deeper look into these diffs and maybe can save the active version - if needed. But I don't think that this is the major use case!?

Normally there should only be cleanup changes (whitspaces, indentation, namings,...) in the inactive version which I just forgot to activate.

Maybe it makes sense to add a repo setting to allow/disallow commits with inactive objects?

**Comment by marcellourbani** [comment]
My point is that if an object class manages inactive versions improperly
what you see in diff and commit to the repo is not what you have on your
instance

**Comment by pokrakam** [comment]
Thanks for linking, as per #2004 I don't think inactive versions should be allowed, ever. 
Dangers are: 
1. Metadata may not be correct, causing #2004 
2. The current active version is serialised and changes are lost

See https://github.com/pokrakam/abapgit_issue2004
The class ZCL_INACTIVE has incomplete metadata, and the source for class ZCL_ACTIVE_CHANGED does not include the method I added.

The user may not be aware of this and the effects may only be noticed far down the line (as was my case).
If someone wants to serialise work-in-progress objects, one can either comment out nonfunctioning parts or force activation. IMHO it's good practice anyway to always leave code in a stable, activated state when stopping work on it.

**Comment by bigld** [comment]
closing - follow up for decision popup will be created
