### ISSUE TITLE
Translation / Language Support and abapGit Questions

### ISSUE THREAD

**Issue by habrahams** [larshp/abapGit#1995]
Hi, 
Firstly, let me say what an awesome project this is! 
I have been playing around with abapGit and abapGitServer to determine if we will be able to use it as part of our development and delivery process.
I do have a few questions though:

1. Does abapGit support multiple languages ? For example a Data Element that is translated into other languages, would abapGit pick up translation changes?

1. Is it possible to pull specific commits on the master branch? For Example,  I have committed C1 -> C2 -> C3 on the master branch  from a DEV system. A consumer(User system) has previously pulled C1, Now the consumer system want to update the solution, but only wants to update to C2, not the latest commit C3. 

1. I mainly use the Java GUI and ADT on MacOs, and have run into a few issues that are already logged as issues. Does abapGit support the Java GUI, or are you mainly focusing on the WIN GUI at this stage?

1. I suspect there will be quite a few object types in our solutions that is not currently supported by abapGit, if I am able to add the unsupported objects, how would I create a pull request via abapGit?

Thanks in advance.

**Comment by larshp** [comment]
1: yes

2: yes, tag your commits, eg one tag for each released version

3: there are problems on the Java GUI, see [open issues](https://github.com/larshp/abapGit/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+java+gui), we will probably move towards supporting ADT instead of Java GUI, but there is a long way to go

4: it is via the [Github flow](https://guides.github.com/introduction/flow/), fork abapGit, install the fork in your SAP system, do the changes, push to the fork, open pull request. Make sure there is open issues for the tasks you are working on 😄

**Comment by habrahams** [comment]
Thanks larshp! 
Much appreciated.

**Comment by habrahams** [comment]
Thanks Lars, yes I have had a look at abapGit-Plugins, and I have read the readme.
Will the objects supported by abapGit-Plugins be migrated to form part of abapGit object support in the future?
