### ISSUE TITLE
refactor CLAS + INTF

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#21]
have 2 serialization classes with some superclass having the common parts

**Comment by larshp** [comment]
closing

**Comment by EduardoCopat** [comment]
There are still pending refactorings:
Methods:

Changed by
has_changed_since
delete
serialize

I will work on that before moving to other issues

**Comment by EduardoCopat** [comment]
I'm reopening this issue and assigning to me because there is still pending items here:

- delete
- serialize

@larshp Question: Currently INTF inherits from CLAS. With this refactoring, should we stop this inheritance even though it leads to duplicate code?

Example: https://github.com/larshp/abapGit/blob/master/src/zabapgit_object_clas.prog.abap#L566

Changed by is the same in both CLAS and INTF, hence, we would need to duplicate this among classes. 

My opinion: Yes, because an inheritance defines a "is-a" relationship. If car inherits from vehicle, car is-a vehicle. Therefore, INTF is-a CLAS?

**Comment by larshp** [comment]
I have recently started factoring common code into a "utillity" class instead of doing inheritance, will this help? (composition over inheritance)
