### ISSUE TITLE
GUI: sap back button instead of html links

### ISSUE THREAD

**Issue by sbcgua** [larshp/abapGit#219]
Following the discussion on the topic at #202 

I'll commit some code in moment which utilize sap back button to navigate through html. F3 also works. GUI stack came very very handy for the task. Done by my experienced colleague who eats sap gui on breakfast :)
Also removed "Execute" button. However the toolbar itself is a bit tricky - still studying, but potentially not possible to hide it dynamically.

BTW "Explore" page does not added to stack and so F3 exits the program.

I've removed Back link at Diff page. For all other I'll do when I come to them because I don't want to break something (or you can integrate it earlier).

**Comment by larshp** [comment]
cool, looks good, will test later today

**Comment by sbcgua** [comment]
BTW, looking at COMMITS at DB logic - I think they should be move somewhere, or the back logic won't work properly (actually commits won't work). I'd suggest dedicating a separate button to save DB changes

**Comment by sbcgua** [comment]
Also page_commit->push

**Comment by sbcgua** [comment]
@larshp returning to the subject of db commits :)
Would really suggest moving them from view (pages) to model. I did a small code overview. Here are problematic places.

`page_commit->push`
For me as a contributor it is not quite clear what is it committing to DB ? If this is related to mo_repo - can we move COMMIT to lcl_repo method ?

`page_main->pull`
Same. Which class does DB updates here ?

`page_main->remove`
Same. Does lcl_repo_srv updates DB here ?

`page_main->uninstall`, `install`, `abapgit_installation`, `new_offline`
Same

`FORM branch_popup`
I would rather also incapsulate that to lcl_sap_package, maybe even lcl_sap_package=>create as it is called immediately and it is called just twice in the code.

`ltcl_dangerous-run`
This one does not block my plans with UI :) But for unified code I guess it should be adjusted as well. 

`page_db_edit->save`, `page_db->delete`
Same, let it be the part of lcl_db

What do you think ? Potentially I could adjust this but, as I mentioned, it is not quite clear which classes actually demand commits without deeper code study (and I didn't go deep to the "backend" by now :)

**Comment by larshp** [comment]
hmm, I'll not recommend pushing commits to the model. Having commits in the model would prevent a sequence of actions being in the same commit. Corresponding to BAPIs would do a commit, instead of the caller being responsible for the commit.

Perhaps we can take the SAP GUI dynpro approach, that each screen step should trigger an implicit commit. Ie. let lcl_gui=>render and lcl_gui=>call_page, lcl_gui=>back do the COMMIT WORK, exceptions would be caught somewhere and trigger rollback. This would be quite simple

**Comment by sbcgua** [comment]
Mmm. Generally agree. Actually the controller class I'm planning to create (if you don't mind ;) can do that. It will be kind of extension of lcl_gui (maybe even merge with it). But how to make it cleaner to use ?
What about some kind of session class? Created in call_page or around. Triggered to "dirty" state by models (it should be singleton probably as there can be only 1 db session in this way). And then controller can commit this session and it checkes "dirty flag" and etc ... Creating a new instance of session automatically rolls back existing "dirty" session (for the case some exceptions caught during previous execution). Just thoughts ...

I can do some tries on the subject.

BTW do you know well how (when!) object construction/destruction works in abap? If I define and create an object and then leave the function/method is it desctructed immediately or later by garbage collector ? Thinking about old C++ trick when debug class was defined as a variable at the beginning of a function and no other debug code was there, the debug class constructor did all debug output and then same for it's destructor implicitely executed upon return from the fucntion. I thinking if it is possible in abap ? :)

```abap
method AAA.
  data o_session type ref to lcl_session.
  create object o_session. " <- some initialization in constructor, rolling back previous sessions ???

  ... code ...

  " here implicit descruction happens, potentially auto rollback if not explicitly commited in code due to exceptions
endmethod.
```

**Comment by larshp** [comment]
objects/data in abap is garbage collected. If the reference is lost there is(AFAIK) no way to get it back.

Pehaps do a small example outside of the abapGit code to see how stuff could look?

**Comment by sbcgua** [comment]
smth like [this](https://github.com/sbcgua/TestRep1/blob/master/db_transaction.abap)

**Comment by larshp** [comment]
hmm, yea

can we make the commit and rollback symmetric? typically I'd expect a commit and rollback to be near each other in the code, something like the following,
```abap
try.
  some logic
  lo_t->commit( ).
catch exception.
  lo_t->rollback( ).
endtry.
```

With the approach we could cache the database updates in internal tables instead of pushing to the database immediately(all database updates happens in lcl_persistence_db), this will avoid implicit commits, and make it up for the dirty flag. Also some protection for doing database updates outside of a transaction(lcl_db_transaction) could be added, which will help reminding the developer to create the transaction object.

I'm still not sure if this is something that we need, currently I have not experienced any problems with database updates. Transaction managers are the correct way to go, and I've built several over the years, but usually they get complex. So I'm worried about introducing extra complexity when it seems like stuff is working.

There are some issues in the current setup, and probably a bunch of theoretical issues. If it messes up for the users, it is quite easy to start over. The remote git repository contains all the important data.

hmm

**Comment by mrsimpson** [comment]
Opposite idea: forget about sessions and caches: Commit after each DB-Interaction. 
Introducing a state (no matter whether in internal tables or in the DB buffer) increases complexity. Though I believe business transactions tend to benefit from state, I don't think ABAPGit needs it: Git commands imply a stateless interaction pattern, so why not make use of that complexity?
Personally, I had thought of coding the COMMIT WORKs ins the Data access class.

**Comment by sbcgua** [comment]
I also think that pushing commits to model is not that bad idea here - all db updates seems atomic: repo synced - update and commit, create package - commit, etc ...

**Comment by larshp** [comment]
good arguments, lets do it, push it down :smile: it should be possible to limit COMMIT WORK to some of the methods in LCL_PERSISTENCE_DB. Guess ROLLBACK WORK will not be needed anywhere.

abapGit is a special piece of software, typically all the normal business transaction software design arguments come to mind. Same thing when we designed the database layout, which ended up in a de-normalized database layout

**Comment by larshp** [comment]
can we close this issue, I think all html buttons have been removed?

the commit push down can be moved to new issue, just to keep this issue on topic

**Comment by sbcgua** [comment]
Agree, closing. :)
