### ISSUE TITLE
SCP1: Text tables are not imported

### ISSUE THREAD

**Issue by p-dmitrij** [larshp/abapGit#2348]
During serialisation of a BC-Set with a text table, the field "recnumber" of language texts is not condensed in the XML:
![image](https://user-images.githubusercontent.com/37515520/52156352-e592d300-2698-11e9-8f00-43000a166283.png)
This leads to a problem by activation of the pulled BC-Set, namely the language texts are not loaded. I've extended a little bit the logic of the methods ADJUST_OUTBOUND() and ADJUST_INBOUND() of the class ZCL_ABAPGIT_OBJECT_SCP1 and now the text tables seems to be working fine. The problem was that the field "recnumber" of the internal table "cs_scp1-scprvall" was not condensed like it was in other 2 tables "cs_scp1-scprvals" and "cs_scp1-scprreca".

This is my correction:

`**Method ZCL_ABAPGIT_OBJECT_SCP1->ADJUST_OUTBOUND()**
...
    LOOP AT cs_scp1-scprvall ASSIGNING <ls_scprvall>.
      CONDENSE <ls_scprvall>-recnumber.
    ENDLOOP.

**Method ZCL_ABAPGIT_OBJECT_SCP1->ADJUST_INBOUND()**
...
    LOOP AT cs_scp1-scprvall ASSIGNING <ls_scprvall>. 
      SHIFT <ls_scprvall>-recnumber RIGHT DELETING TRAILING space.
    ENDLOOP. 
`

Could you check it please.

**Comment by larshp** [comment]
guess this can be closed?

**Comment by p-dmitrij** [comment]
Give me some time, I will test the correction and close the issue

**Comment by sandraros** [comment]
@p-dmitrij @larshp I think we can close the issue: I just did a test, without the modifications of commit de7dfea3d3e8ebb06a1e688052f7c4e278ef345f (in fact, by debug, I skipped the 2 `LOOP AT cs_scp1-scprvall` added), and then with the modifications. I used SM30 BALOBJ for the test. The text table is BALOBJT.

Note that I had a diff on the BC set after the push and after the pull, before the correction, because of issue #2571 which removes the leading spaces during the deserialization.

# Before correction

## In the source system, before push

![image](https://user-images.githubusercontent.com/34005250/55287536-7a206580-53aa-11e9-9489-22b39341a45d.png)

## In the Git repository (zzzzz.scp1.xml file)

![image](https://user-images.githubusercontent.com/34005250/55287566-ed29dc00-53aa-11e9-83bb-29266c9f20b1.png)

## In the target system, after pull and BC set activation

![image](https://user-images.githubusercontent.com/34005250/55287676-4c3c2080-53ac-11e9-9bd7-f5670163efda.png)

![image](https://user-images.githubusercontent.com/34005250/55287645-fbc4c300-53ab-11e9-87b6-7af37af2cb67.png)

![image](https://user-images.githubusercontent.com/34005250/55287630-c91aca80-53ab-11e9-99bf-a2e4a545a4c1.png)

![image](https://user-images.githubusercontent.com/34005250/55287623-aa1c3880-53ab-11e9-99cd-7515b1a02150.png)

# After correction

For the test, I just suffixed the text with "2" and did a "supplement" of the existing BC set to load the new text.

## In the source system, before push

![image](https://user-images.githubusercontent.com/34005250/55287844-beae0000-53ae-11e9-9f58-fd90149ddf6e.png)

## In the Git repository (zzzzz.scp1.xml file)

![image](https://user-images.githubusercontent.com/34005250/55287801-0a13de80-53ae-11e9-98f6-785b0746af18.png)

## In the target system, after pull and BC set activation

![image](https://user-images.githubusercontent.com/34005250/55287815-56f7b500-53ae-11e9-9683-e3d17b0b0da2.png)

![image](https://user-images.githubusercontent.com/34005250/55287856-e7ce9080-53ae-11e9-813f-486a39a891d8.png)

**Comment by larshp** [comment]
thanks, closing

**Comment by p-dmitrij** [comment]
@sandraros Thank you for the testing!
