### ISSUE TITLE
SCP1: Not deserialized properly at first time

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#2418]
When installing https://github.com/abapinho/abaK.git business configuration set (SCP1) ZABAK_TABLE_CUSTOMIZING isn't deserialized properly. 

![image](https://user-images.githubusercontent.com/17437789/52914316-37597100-32c7-11e9-8a13-605cbe970cf8.png)

![image](https://user-images.githubusercontent.com/17437789/52914256-8b178a80-32c6-11e9-9817-65daedb95b1f.png)

'Reset Local' then installs the object correctly.

**Comment by nununo** [comment]
Hi @larshp, I am about to commit a new version of abaK which makes changes to this particular object. Let me know if you want me to wait (to avoid destroying the example before you can look at it) or if I can go ahead and commit.

**Comment by larshp** [comment]
go ahead and move along with your project

I've forked the current status of the repo to https://github.com/larshp/abaK, anyhow we should build a test case for abapGit-tests organization

**Comment by goreraks** [comment]
When the BC Set is packaged for a table and the table creation + table maintenance generation are in the same repo, then BC Set is not deserialized correctly.
Clone https://github.com/abapGit-tests/SCP1/pull/1 to reproduce the issue.

**Comment by goreraks** [comment]
Changed the deserialize step to 'LATE' for object type SCP1, still the issue was not fixed because during late import the SOBJ definition i.e. object type TOBJ is imported.
Since it is the alphabetical order, the TOBJ is imported only after import of SCP1.
![image](https://user-images.githubusercontent.com/58498218/85136039-a4cf3600-b25c-11ea-9e35-b10c8f16da2b.png)
