### ISSUE TITLE
http authentication, investigate OAuth

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#252]
Is it possible to use OAuth for saving "passwords"

trouble will be the callback URL, but perhaps it can work with some "sapuri://" stuff

**Comment by larshp** [comment]
closing

**Comment by NaveenKurmadas** [comment]
@larshp, I want to authenticate using OAUTH and not basic authentication when pushing my changes to Git. Is it already possible? If not, is there some exit or BADI where i can write my own code to switch authentication from Basic to OAUTH in ABAPGIT?

**Comment by larshp** [comment]
currently not possible

see https://docs.abapgit.org/ref-exits.html, exit CREATE_HTTP_CLIENT can be used, anyhow if you find a solution then pull requests implementing this feature are welcome

**Comment by NaveenKurmadas** [comment]
@larshp Thanks for the information. I will use this exit and switch authentication to use OAUTH instead of basic.
I have already implemented a code which does OAUTH based authentication to Git repository using Authorization code grant and it works. Now I will integrate this solution in abapgit and will give a try. 

Thanks and Regards, 
Naveen

**Comment by larshp** [comment]
cool, can you share the proof of concept code?

**Comment by NaveenKurmadas** [comment]
Sure, I will share the code when i'm done with integrating with abapgit. Thanks.
