### ISSUE TITLE
UX Feedback

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#2572]
## Abapgit button, breadcrumbs

The big abapgit button being a link to the abapgit repository is not very useful as it is not a frequent action for most users. It could be replaced with a link to the main page instead.

Then these could be breadcrumbs:
![SapGuiServer_O5fnEUwajh](https://user-images.githubusercontent.com/5097067/54900253-d11dca80-4ed2-11e9-84e7-f835eeed44c9.png)

e.g. clickable `repository` -> `stage` -> `commit` which could be used instead of back buttons.

The button at the bottom where the version is stated is where I would expect a link to a repository or docs. It is currently not clickable.
![SapGuiServer_EKfVHTJysI](https://user-images.githubusercontent.com/5097067/54900248-ccf1ad00-4ed2-11e9-9870-0e0e70ea0285.png)

## Links

In the main/stage screens, this is a link to the repository:
![SapGuiServer_oeBoFm1RHK](https://user-images.githubusercontent.com/5097067/54900361-370a5200-4ed3-11e9-995c-8e932a3a705a.png)

In the diff page, the filename should be a link to the (online) repository. An ADT link should be there as well so I can open both the local and the remote version.
![SapGuiServer_r5Z6PnQcDI](https://user-images.githubusercontent.com/5097067/54900371-4093ba00-4ed3-11e9-934f-69eab47a7455.png)

The stage filter could have a `links` column with three links/buttons: `local`, `diff`, `repo`
![SapGuiServer_yl7mX7lLRh](https://user-images.githubusercontent.com/5097067/54900791-dda32280-4ed4-11e9-9513-ebbce6f665e5.png)

## Stage page filtering
The filter here is not as powerful as on the diff screen. I can't search in multiple columns, e.g. search for username + extension.

![SapGuiServer_yl7mX7lLRh](https://user-images.githubusercontent.com/5097067/54902261-2e1c7f00-4ed9-11e9-94b4-a2db4188b9f0.png)

Ideally this filter along with a fulltext search would be accessible in all pages where files are listed.
![SapGuiServer_N7S2v6qL1Q](https://user-images.githubusercontent.com/5097067/54902282-3a084100-4ed9-11e9-9b6d-02c9cca14188.png)

## Opening in external editor
Would it be possible to have a link such as this next to the repository link? Not sure if there is a way to set the default program for such links.

the link goes to `x-github-client://openRepo/https://github.com/larshp/abapGit` and the visual studio link opens `git-client://clone?repo=https%3A%2F%2Fgithub.com%2Flarshp%2FabapGit`
![chrome_8VFHXwILcJ](https://user-images.githubusercontent.com/5097067/54902304-4a202080-4ed9-11e9-8a5c-ef8948ff32f5.png)

## Transport to branch:
I can transport a task, but I can only enter a request ID, not a task ID. Then I have to find the task manually.
![image](https://user-images.githubusercontent.com/5097067/54902423-a7b46d00-4ed9-11e9-8f7f-4113b05eac9d.png)

Could the initial branch commit message be taken from the request/task longtext?
![eclipse_DALVFNbsOW](https://user-images.githubusercontent.com/5097067/54902400-94a19d00-4ed9-11e9-9344-3ba2e0647ddf.png)

**Comment by sbcgua** [comment]
Great feedback, thanks !

Opinions/questions from my side:

## breadcrumbs

1) Logo - link to main page. Agree. But do you mean current repo page or the tutorial ? (imho it should be the home page which is the tutorial at the moment)

2) Clickable breadcrumbs. Interesting idea, but a bit arguable since the long breadcrumbs will be just in repo->stage->commit scenario. Also how to represent "repo" link in this case ? If it is on abapGit logo - it is not obvious. If it is a separate text chunk - may take a lot of place. So idea is good but need more detailed elaboration imho

3) Imho I'd remove the bottom logo at all. @larshp ?

4) Link to docs is a very good idea imho. +1

## Links

1) *"link to the repository"* - do you mean making repo name a link and remove url ? In general I'd be for it. But one concern. Let's say a have a fork. From URL I immediately see that it is a fork, not the original repo. I personally think this is valuable - e.g. AG is installed in several systems I have access to but only in one it is my fork and control visually not to commit to the wrong repo occasionally. Maybe, we can hide the url but show the first portion of the url to indicate the namespace - like "id-ifme [abapgit]" ?

2) *"the filename should be a link to the (online) repository"*. Good idea, just to double check that the link can be formed universally (since there is not only github)

3) *"ADT link should be there"*. Any suggestion on how it should look like ? 2 links side by side ... could be confusing.

4) *"The stage filter could have ... local, diff, repo"*. It has diff link, file name is clickable. local/repo - imho I'd leave it for diff only. For me logic is the following: I go to stage - see unexpected file - go to diff to see the changes - stange changes ? - let's see the whole object or fix it.

## Stage page filtering

1) *"I can't search in multiple columns"*. +1. P.S. Just would keep it in JS, not in abap.

2) *"Ideally this filter along with a fulltext search would be accessible in all pages where files are listed"*. Hmm, example ?

## Opening in external editor

Good idea, just not sure how to form the url universally. Protocol handler are not standartized, any program can implement own proto prefix and register it in the OS.

## Transport to branch

Cool. +1
But 2 comments:
1) What if there are more than one transports ?
2) What if certain repo/system does not use transport management e.g. for some developments I just put everything in one transport and never release

**Comment by FreHu** [comment]
_Logo - link to main page. Agree. But do you mean current repo page or the tutorial ? (imho it should be the home page which is the tutorial at the moment)_

This could depend on
![image](https://user-images.githubusercontent.com/5097067/54916774-93349c80-4efa-11e9-8c45-0d614f4f2473.png)

so everyone is satisfied. Personally I'd most likely use the current repo but maybe someone manages multiple and the default repo serialization is slow so they would like to avoid that.

_Clickable breadcrumbs. Interesting idea, but a bit arguable since the long breadcrumbs will be just in repo->stage->commit scenario_

There is also `repo->stage->patch`. What I'm actually trying to solve by this is avoiding loading multiple screens when needing to go back multiple steps, which unnecessarily slows the user down (and might eat some processing time, although the stage screen is quite fast to load).

Whenever I need to do this I'm always inclined to use the second back button in SAPGUI, but this instead quits the transaction. Maybe the behavior of this button could also be changed to go home, so there would be `back`, `home`, `quit`, but I think the UI should be independent of SAPGUI.

_Also how to represent "repo" link in this case ?_ 
I agree that the abapgit button would become confusing. I think you don't need to advertise abapgit there anyway as it's right above as well:
![image](https://user-images.githubusercontent.com/5097067/54917595-713c1980-4efc-11e9-873a-7ea84407a4b0.png)

TODO mockup which recycles existing parts.

_Imho I'd remove the bottom logo at all? Link to docs is a very good idea imho. +1_

The logo is fine, everyone has one of these standard footers:
![image](https://user-images.githubusercontent.com/5097067/54917700-a47ea880-4efc-11e9-9140-f5b74fe74eff.png)

![image](https://user-images.githubusercontent.com/5097067/54917704-a9dbf300-4efc-11e9-886e-78bdf5127611.png)

But the version and js:ok message could easily fit on the same line as the logo with some additional links for opening an issue/docs:
![image](https://user-images.githubusercontent.com/5097067/54917771-d859ce00-4efc-11e9-83ba-b20ec75e0b30.png)

...rest to follow at some point

**Comment by sbcgua** [comment]
Seems like no one else joins the discussion :)
I guess let's either split it into several tickets or at least areas or make a todo list from it :)
I can participate in some of tasks if needed, I like UX  :) I can do diff for example.

Brief replies

- logo link depends on config - yes, cool, I actually missed that this settings is there :) it resolves the question.
- hijack "yellow back button" as home - good idea, I'm far from expert in this but I have a feeling that it should be possible
- breadcrumbs: I think "repo name -> stage -> commit" is a nice header. I'm OK with removing the logo or leaving the git logo only. But this question also has marketing aspect :))) @larshp, what do you think ? Technical comment - in fact, the stack of pages is present in ZCL_GUI->mt_stack ... so just need to find a proper way visualize it.
- bottom logo - imho very good ideas with links to docs and issues. Why did we do it before ? =)) Also the home github page can be there instead of head logo
- diff file - menu on filename - I was thinking about icons near the name. Probably prototyping is the way to check.
- freetype filter on the repo page - yeah, could be useful indeed ... also maybe to do a partial import ??
- transports: well, I'm not using this feature to be honest. At least yet. So would vote that it is not the obligatory way, there should be an option to turn it on/off for a certain repo imho.

**Comment by FreHu** [comment]
Feel free to split this, I didn't want to create a bunch of issues immediately.

**Comment by FreHu** [comment]
see references
