### ISSUE TITLE
Use pseudo comments for older systems

### ISSUE THREAD

**Issue by GiantCrocodile** [larshp/abapGit#2574]
At some lines of the source code, there are pseudo comments or pragmas used. Pseudo comments should be used for older SAP systems. These pragmas are unknown according to my SE80:

- SUBRC_OK
- WARN_OK
- ENH_OK

**Comment by flaiker** [comment]
In my opinion these warnings on older systems are fine. There's no negative effect from a user's point of view. From a developer's point of view pragmas have the advantage that an existence checked is performed on compilation / syntax check (and otherwise that raises a warning).
With the AS ABAP Developer edition it is easy to develop abapGit on a recent release so I don't see the benefit of replacing the pragmas.

**Comment by larshp** [comment]
@flaiker agree, closing
