### ISSUE TITLE
Commit leads to empty process stage list

### ISSUE THREAD

**Issue by enyangxxx** [larshp/abapGit#2769]
Precondition:
1. Do code changes within a package, which is connected to a repository by abapGit
2. Click "refresh" and "stage"
3. Add single object/file to commit (by clicking the "add" button on the right side of the question mark)
4. Click "Commit"

Expected behavior:
The commit should process successfully

Actual behavior:
I get an error message: process_stage list: empty list

Is it a known issue? If so, how could I fix it? Thanks in advance :)
<img width="895" alt="add-single-file" src="https://user-images.githubusercontent.com/32799307/60432292-2ec46000-9c02-11e9-9bc4-3c6d2e05d116.png">

**Comment by christianguenter2** [comment]
Works for me. After pressing "add" does it change to "reset" like this?
![image](https://user-images.githubusercontent.com/17437789/60449138-48c46980-9c27-11e9-9fdd-07b7ecf1a84c.png)

Do you use SAPGUI for Java? There are some issues there pointing in that direction.

**Comment by larshp** [comment]
is it possible to determine if the gui is java? if so perhaps we should display a warning/information message

**Comment by larshp** [comment]
@enyangxxx see questions above

**Comment by michelmartin** [comment]
I'm experiencing the same issue when adding a single file: "process_stage_list: empty list" error.

1. I have tried the most recent ABAPgit, does not work either. 
2. I am using SAPGUI for Java on a Mac.
3. Reset does not help at all.
4. If I instead choose "Add all and commit", it works.

**Comment by larshp** [comment]
yea, see readme, "Recommend using SAP GUI for Windows, there are multiple issues related to running abapGit and Java SAP GUI. Focus is on supporting ADT instead of supporting Java SAP GUI."

**Comment by enyangxxx** [comment]
Hi! Thanks for the reply, I am using Java SAP GUI actually on Mac too, sadly.. But thanks a lot still :)

**Comment by larshp** [comment]
due to Java GUI, closing

**Comment by jfilak** [comment]
@enyangxxx @michelmartin I cary this patch https://github.com/filak-sap/abapGit/commit/6889f171753cac9a71e24382744a1c70f122cb73 on top of the upstream abapgit. The patch fixes the problem with empty commits in Java GUI for me.

**Comment by michelmartin** [comment]
@larshp Is it possible to consider merging this patch? I know the focus is the ADT client, but it's limited to SAP Cloud Platform ABAP Environment, hence does not work on traditional ABAP backends. As far as I worked with it, that's the only issue I am facing.

**Comment by larshp** [comment]
hmm, @jfilak suggest opening it as a PR, then we can take a look 😄

**Comment by jfilak** [comment]
@larshp Sorry, you already refused that patch - https://github.com/larshp/abapGit/pull/1932#pullrequestreview-162814640

**Comment by larshp** [comment]
the patch filak-sap@6889f17 is less than half the size of PR #1932 

and much more logic has been added in javascript without problems, a year ago this was not the case

plus we have seen more issues opened regarding java

and I guess the patch has also been tested more

**Comment by larshp** [comment]
plus we have not had as much progress on the ADT frontend as could have wished

**Comment by rayatus** [comment]
I had this same error today while in ABAPGit "1.119.0 - Developer Version" and "SAPGui for windows 7700.1.8.1161"
When I clicked on STAGE, added a single class, then clicked on COMMIT and following screen was shown (sorry in Spanish), let me translate it for you:

"information you are about to send is not secure.
due to this form is being sent via non secure connection, the information will be visible by other users."

![image](https://user-images.githubusercontent.com/12736990/205340729-ce804571-1b26-4ae0-8680-c53660f12e39.png)

then, automatically that webpage disapears (it stays on screen for less than 1 second) and finally following error: 
![image](https://user-images.githubusercontent.com/12736990/205341710-74f5eec1-9b3c-4512-b997-b7ae6b2a0dc8.png)

CallStack was 

![image](https://user-images.githubusercontent.com/12736990/205341629-04cfe2be-c43f-4dc4-b79b-cdab22c1dc42.png)

and source was

![image](https://user-images.githubusercontent.com/12736990/205341835-2be5cb64-67e0-483d-8048-f52cea32a142.png)

In case it may help:
Folder Logic -> FULL

**Comment by christianguenter2** [comment]
Can you check your Browser Control settings?
https://docs.abapgit.org/guide-install.html#prerequisites
