### ISSUE TITLE
Works only with local packages?

### ISSUE THREAD

**Issue by e4rthdog** [larshp/abapGit#3064]
Obviously not, but i cant make abapgit work with existing packages.

Tried the docs but werent clear for me. I need for example to GITify my existing packages.

I tried with +Offline with a normal package. when i did and and export the .zip file the source was there.

When i made a change in a report in that package, abapgit did not bring the file as changed.

How do i suppose to enable git with my packages? I havent set up SSL yet with gitlab so i am trying with the +Offline method. Local packages work ok.

**Comment by mariusraht2** [comment]
For online/offline repos both package types work. For offline repos changes can't be recognized by abapGit because it just generates a zip file and isn't linked to a repo (e.g. on your computer) so it can't compare the repo with anything. If you use an offline repo and download the zip file to your computer you have to decompress the file and sync the repo with your git provider yourself via Git Bash, e.g. for Windows https://gitforwindows.org/. There are many tutorials on the internet how to do this, e.g. https://www.atlassian.com/git/tutorials/git-bash.

**Comment by e4rthdog** [comment]
> For online/offline repos both package types work. For offline repos changes can't be recognized by abapGit because it just generates a zip file and isn't linked to a repo (e.g. on your computer) so it can't compare the repo with anything. If you use an offline repo and download the zip file to your computer you have to decompress the file and sync the repo with your git provider yourself via Git Bash, e.g. for Windows https://gitforwindows.org/. There are many tutorials on the internet how to do this, e.g. https://www.atlassian.com/git/tutorials/git-bash.

My misunderstanding was that you cant compare with anything so my question was stupid cause it is normal not to see any changes in sap gui. You would have to sync it offline....And i could use other branches also but that would mean to maintain the source code on my laptop and do that, Which is something that i will try.

Next is to try the full online way and have everything in order. thank you and sorry for the unneeded question :)

**Comment by mariusraht2** [comment]
@larshp Can be closed.
