### ISSUE TITLE
switch branch - possibility to switch repo url

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#319]
when switching branch it should also be possible to change the repository URL

In case someone installs eg. abapGitServer, and later finds out changes are needed in a fork. It should not be required to uninstall the project, as it will delete the contents in the database tables

**Comment by sbcgua** [comment]
@larshp that was my change to close the field :)

I can open back, but:

1. In term of UX it is better to separate the commands - swtch branch/ switch url. Less prone to casualties.
2. I plan to make some functionality for attached/detach offline repo to online origin. This will be in fact what you describe. Although I cannot state any deadlines ;)

**Comment by larshp** [comment]
1. agree, just need the functionality somewhere
2. cool, open source = no deadlines :smile:

**Comment by sbcgua** [comment]
As this topic is started maybe it worth to discuss a bit. Here are some thoughts.

The scenarios I see:

1. Clone online repo - **exists**
2. Create offline repo - **exists** - here I don't quite like the term, it's not creating anything ... maybe should choose something better. Maybe just "add offline package" or similar
3. Detach or Unlink online repo from online -> resulting an offline repo
4. Attached or Link offline repo  to online origin -> resulting an online repo. Important: this supposes that online repo is actual and local one pulled.
5. Deploy local to online -> resulting online repo - This one, on the opposite, supposes that local repo is more up-to-date. Main usage imho is first publish of the code (maybe 'Publish' is better term btw)
6. Create offline + deploy. Actually = 2 + 5 so low priority and can be skiped for the moment. 
7. Switching the origin. = 3 + 4.

Probably 4 and 5 can be combined in one UI with choosing the option somewhere by the way.
Another question is how to manage non-code files, especially in deploy (licence, readmy and other stuff which might be in a newly initiated repo)
Yet another question is choosing source dir. So actually some kind of on-the-fly `.abapgit` configurator.

**Comment by larshp** [comment]
2. agree
3. is this needed? what would the typical use case be? Maybe the application server is moved behind a firewall 
4. -
5. as described in https://github.com/larshp/abapGit/wiki/Moving-existing-package-contents-into-git ? it is currently not super user friendly, but it works
6. can be done as described above
7. there is no need to make it offline first, we can just change the `url` in the online repo and it will work

The non-code files would not exist in an offline to online deploy scenario, they would have to be created manually later.

Choosing source dir? I'm not sure we agree on the terms used. Deploy local would this be choosing a directory, or as the current approach choosing a zip file?

**Comment by sbcgua** [comment]
3) Well, indeed looks like something rare ... but if there is an action (attach) in UI there must be an contra-action :) Actually the feature seems to be trivial to implement. 
5) OK, then I'd suggest making it clearer. It should be obvious from the interface. E.g. recently I had this issue with one repo and I had to manually play with DB-util (I overlooked this wiki article). Just a sample of user feedback. :)
7) OK

**non-code files**: I mean the case if I have a repo (or maybe someones repo) I installed it manually locally and adjusted. And now I want to contribute changes. Kind of add origin for local git. If I understand correctly if I do it now with DB-util, abapGit will first want to make pull because of "new" remote files which were not excluded. This is a bit contra-intuitive. Although not a big issue of course. Actually how I imagine it: deploy should probably show Commit page and that page should show also "new" remote files asking to exclude them or to resolve conflicts before commit (if they are code-related). Something like this. 

**deploy dir**: I mean, what should I do if I want to deploy to /src/ directory remotely. (maybe I also overlooked something in the wiki on this topic ... :)

**Comment by sbcgua** [comment]
halfway (well, less frankly ;) ...
Got one issue: I want to clear `sha1`, `head_branch`, `branch_name` when switching to offline to remove ambiguos info from XML. But persistence calls asserts those are not initial (`update_***`). Not sure what to do. Asserts look good, but how to remove XML clutter then ?

**Comment by larshp** [comment]
just remove the validations

**Comment by sbcgua** [comment]
@larshp would you mind if I refactor lcl_popups a bit by the way ? There is too much "business" logic in it (many repo calls).

**Comment by larshp** [comment]
give it a try

however wont the repo calls just be moved to somewhere else, introducing another layer to ensure reusability?

**Comment by sbcgua** [comment]
I'll check. I didn't study it much yet. My current idea is that calling to repos would look better in router (or where the command is actually handled). Maybe this will result in some double code ... potentially ... or maybe not. But currently tracing repo-changing code down to lcl_popups is really confusing. Popups is utility class (should be). Seeing repo calls there without context is confusing imho.
Maybe it is worth to introduce some git_services class which will implement high level logic like close/switch/etc. Then it can be called from router and other places.

**Comment by sbcgua** [comment]
... maybe this class is `lcl_repo_srv` by the way.

**Comment by sbcgua** [comment]
Seems to be done ... But:
Could you pls check `services_repo->remote_attach` and `remote_change` logic for those git calls ?
If I detach repo, and then attach it - it shows Pull first (expected), but then when I Pull it shows Stage immediately while there are no changes. Well, in this particular case I actually changed remote file after detach - but then Pull should have update the local copy (and it did!) - still it shows empty stage. Strange.

If fine then I'll PR

**Comment by larshp** [comment]
just create the PR, then I'll take a look, it is a bit easier with the PR created

**Comment by sbcgua** [comment]
Now I'm thinking about attach vs deploy (Pull first or Stage first) and really not sure how to do it properly. The problem in imho is that abapGit does not track the history of changes and do not have own merge/conflicts logic so it cannot decide what should happen - it is the human who must choose. But at which moment ?

Curently home_page renders Pull if it is available and surpresses Stage. What if they are rendered  independently ? What is the worst that can happen - I have updates in remote and dirty local state. Then I commit. So some remote updates may be overwritten. But there is a history there so it can be restored (although not with ag).

**Comment by sbcgua** [comment]
UPD: I mean that I attach repo and then I have both Stage and Pull (Pull however is there mainly because sha1 is empty in repo-cfg !!! Is it a problem ?)

**Comment by larshp** [comment]
not sure about the context, what are we trying to solve? there is a lot of history in this issue...

**Comment by sbcgua** [comment]
=) It is about deploying. Let's I want to post initial commit from system to remote repo. 
Now if I attach repo to remote I see Pull ! But I want to Stage !

More complex case: I detached repo (or imported it somehow manually) and did some coding. Now I want to commit it. So I attach the repo and what to stage.

Even more complex: 2 + someone also did some changes in remote repo.

**Comment by larshp** [comment]
I think its okay to force the user to do the pull first, or we will have to handle more scenarios.

Should just be able to make sure no local changes are overwritten #337

**Comment by sbcgua** [comment]
Ok, final adjustment. Now Pull and Stage displayed independently. And if repo content is identical after commit - branch sha1 is updated (this hides Pull, which otherwise had to be technically pressed always after re-attaching).

P.S. Just by the way (I initially went really wrong way) I added sha1 to file structure and its's update in `repo->get_files_local` and pull routines. After it was a pity to remove it so it stayed. Maybe it could be useful in some other places. But I can remove if you say.

**Comment by larshp** [comment]
hmm, does this means that when pulling a 731 object to 750, there will most likely be something that does not match, and after the pull the 'Pull' option will still be visible?

**Comment by sbcgua** [comment]
Pull should behave the same: meaningful changes are:
- main_page renders Stage button **even if** Pull is there
- After commit files are compared and if they are similar then ms_data-sha1 is updated so that Pull does not appear next time (from what I know this is relevant only to attach, when sha1 is empty)

**Comment by larshp** [comment]
ahh, okay :+1:
