### ISSUE TITLE
Multiple SICF with identical names is not imported

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapGit#3230]
Trying to pull a repository, a SICF object cannot be imported.

This is caused because, at import, it determines that the object exists because it is searching a pattern in TADIR that found an incorrect entry:

This is the logic to read TADIR entry:
![image](https://user-images.githubusercontent.com/56556686/75763866-3a41cb00-5d3d-11ea-850f-be807b7a08ae.png)

And this is the TADIR table in the original system:
![image](https://user-images.githubusercontent.com/56556686/75763900-4b8ad780-5d3d-11ea-8ca6-2aa3e5a7a7ce.png)

**Comment by larshp** [comment]
ugh, so there is multiple nodes with the same name? this might cause some issues

**Comment by jrodriguez-rc** [comment]
This is because there are services under a namespace, when a namespace is used a new node is created to use it instead sap/ node
![image](https://user-images.githubusercontent.com/56556686/75764487-38c4d280-5d3e-11ea-9309-41f122cdeebb.png)

**Comment by larshp** [comment]
hmm, this is difficult, the SICF serializer contains hacks

**Comment by jrodriguez-rc** [comment]
We can try to use full path to determine the correct SICF when reading from TADIR

**Comment by larshp** [comment]
I dont remember exactly how it works, just that its kind of mess

suggestions welcome

**Comment by jrodriguez-rc** [comment]
After #3223 I'll check possibilities about this

**Comment by jrodriguez-rc** [comment]
To have located the problem I found in `zcl_abapgit_object_sicf->read_tadir_sicf`

```
    IF lines( lt_tadir ) = 1.
      READ TABLE lt_tadir INDEX 1 ASSIGNING <ls_tadir>.
      ASSERT sy-subrc = 0.
      rs_tadir = <ls_tadir>.
    ENDIF.
```

**Comment by Elberet** [comment]
Seems we have stumbled across the same issue. For now, I've comment out the `IF lines( lt_tadir ) = 1` block @jrodriguez-rc mentioned above; this allowed AbapGit to import our services correctly, but is probably not a good solution in general.

However, it might be the only option here, unless AbapGit wants to maintian a database of the ICF node IDs so that it becomes possible to map remote to local services by their immutable node ID rather than the mutable URL.
