### ISSUE TITLE
Patching directly from repo page

### ISSUE THREAD

**Issue by FreHu** [larshp/abapGit#3266]
On the repo page, place a `Patch` button after `Stage`.

If this was possible I would often go straight to patch, skipping the stage screen. I think it would still be required to serialize everything again, but you get the slight productivity boost of skipping a page load.

**Comment by sbcgua** [comment]
Opinion. The command bar is already too crowded. Adding a button will make things worse. I think we should think how to organize the command better. E.g.

- Branch and tag has very close function. I'd propose to unite in one menu (with groups "branch" and "tag"). Perhaps event push a bit further and create a common interface for both with fuzzy search ?
- Rename "Show diff" to "Diff" :)
- Unite Stage and Patch into a submenu ? + keyboard shortcut ? This however has a negative side effect. Stage is by far more used function, forcing users to "move mouse to Stage and then to Stage suboption" is bad :( One idea is to create a new control for this - dropdown which stays on the same place so that "stage suboption" would be under cursor on hover (I can create a mock for this if unclear). Idea 2: maybe just add Patch as a mode to diff page ? The dynamic one (js) so that it does not need to re-render ? Imho this could be similar in terms of UX ?

**Comment by FreHu** [comment]
- I've never used tags, not sure about their adoption in abap
- You can create a branch from the branch popup, if overview and deletion was also possible from there the button could go away
![image](https://user-images.githubusercontent.com/5097067/77225407-18cf4480-6b6f-11ea-84b7-e143ed8bbbbb.png)
- I agee to shorten `Show diff`, I'd also change `All diffs` on stage page to `Diff`

**Comment by FreHu** [comment]
Closing in favor of #3551.
