### ISSUE TITLE
REPO-Settings: Local code inspector check variants are not found

### ISSUE THREAD

**Issue by ed-holland** [larshp/abapGit#3462]
When entering a local check variant, the error "No valid check variant <name>" comes.
Global variants are found.

**Comment by larshp** [comment]
the check variant in repo settings is global for all developers, ie the check variant should also be global

**Comment by ed-holland** [comment]
Then the documentation needs to be adjusted as it states that both are possible. I could see a case during setup that one would like to use local variants so that no others use it.

If you still want to keep it globally, i will adjust the documentation accordingly

**Comment by larshp** [comment]
yea, update the documentation to reflect the implementation

**Comment by GiantCrocodile** [comment]
I will review this @ed-holland. I think I did add the sentence you refer to in the past. Right now, I don't remember if I meant global check variants which are local stored compared to global check variants which are coming from a remote ATC scenario.

So there are two contexts where these terms are used:
- local (one user) vs. global (all users) check variant
- local (not remote) vs. global (check variant from remote ATC system)

I might clarify this better. Sorry for confusion!

**Comment by ed-holland** [comment]
If i remember correct either from local or remote system, it has to be a global check variant.

**Comment by ed-holland** [comment]
Documentation was updated with #3466

**Comment by GiantCrocodile** [comment]
Thanks for updating it @ed-holland. What do you think about adding this for further clarification:

`By entering a Code inspector or ABAP Test Cockpit (ATC) check variant, the check is activated. Only global check variants are supported. Thus the check variant has to be available to all developers. A check variant can either make use of local checks or a reference to a check variant on a remote ABAP Test Cockpit system. The available checks on a remote ATC system may differ from the available checks of the developer system due to the ATC system being on a newer release. For more details about the release-specific availability of ABAP Test Cockpit checks see SAP Note <insert ID here>.`

If you agree, I will create another PR with reference to this issue and add the SAP Note ID I refer to in the text.

**Comment by ed-holland** [comment]
Yes please do. You seem to be more a documenter then i am.

**Comment by GiantCrocodile** [comment]
Haha for sure not. Your PR is fine and especially it's right. My previous wording was misleading and I just invested a lot of work time into ATC topic and thus I'm quite aware what might be surprising/unclear to others or how annoying it is to find relevant information about ATC or how it works. That's why I want to document as much as possible to prevent that me or others have to reread it all time.
