### ISSUE TITLE
Error Deleting Branch

### ISSUE THREAD

**Issue by habrahams** [larshp/abapGit#3636]
There is an error while trying to delete a branch. The branch that I am trying to delete was committed to Github.
![image](https://user-images.githubusercontent.com/16045067/87515509-3a06f400-c67c-11ea-9cac-d15a74bb326a.png)
![image](https://user-images.githubusercontent.com/16045067/87515246-d7adf380-c67b-11ea-94f0-7c393a8a4ca1.png)
![image](https://user-images.githubusercontent.com/16045067/87515282-e85e6980-c67b-11ea-8383-ebc2a6ff7f75.png)
![image](https://user-images.githubusercontent.com/16045067/87515328-fca26680-c67b-11ea-9914-519cae4caa00.png)

**Comment by larshp** [comment]
the "unpack not ok" is an error from the git code

is this something that can be reproduced? What are the steps to create the failing branch?

**Comment by habrahams** [comment]
1. Create a normal local branch from master in abapGit. 
2. Make a smal change, and commit branch to GitHub.
3. Switch to master branch in abapGit.
4. Try to delete branch in abapGit

**Comment by mbtools** [comment]
I can reproduce the issue also with other repos. 

ZCL_ABAPGIT_GIT_TRANSPORT->RECEIVE_PACK   
lv_buffer = '007C5caf2d81cb663407d6a981152ac6ea56c6b25a56 0000000000000000000000000000000000000000 refs/heads/test-branch# report-status#0000'
looks good to me
HTTP 200 but no data in response XString{0} ?!

I recently update the *.github.com cert in STRUST since it was expiring. Related?

**Comment by mariusraht2** [comment]
was able to reproduce it too

**Comment by mariusraht2** [comment]
Comment says pack has to be empty but iv_pack is filled: e.g. 5041434B0000000200000000029D08823BD8A8EAB510AD6AC75C823CFD3ED31E

I emptied it and now the branch could be deleted.
