### ISSUE TITLE
Namespaces / naming conventions for projects

### ISSUE THREAD

**Issue by flaiker** [larshp/abapGit#369]
Looking through this project one topic I have so far not found any discussion on is namespaces and naming conventions. Not in regards to source code but to the development objects themselves. If I start a project which I want to share as freely available to install on anyone's system (and to contribute to) I also want to make sure the objects do not conflict with any of the ones already on the system. Not sure how ababgit handles conflicts right now.

This seems to be especially problematic in SAP development because packages do not restrict the namespaces of the objects they contain but rather every object has to be named in a unique way. Renaming objects and their uses is also extremely painful / impossible (dynamic programming). Another restricting factor is the limit length object identifiers (think of database tables).

The *normal* / proposed solution by SAP of reserving namespaces (/namspc/) seems to not be an option in this regard. People wanting to contribute to a project cannot do it because the namespace is reserved (and all their changes would be modifications). So only the customer namespaces Z and Y can be used which customer development on the system as well as all abapGit projects (!) share. With an increasing amount of projects collisions in namespaces seem to be unavoidable.

Some solutions I thought of (none of which seems incredible practicable):
  1. Reserve top level package names at a central registration and use the package hierarchy as part of every objects name
    - For example I reserve ZFL and could have a project layout like this:
      - ZFL (top level "vendor" package)
        - ZFL_PLM (project package)
          - ZFL_PLM_MODELS (subpackage in project)
            - ZCL_FL_PLM_MODELS_ABST_PLANE (class)
            - ZCL_FL_PLM_MODELS_CARGO_PLANE (class)
          - ZFL_PLM_DICT (subpackage in project)
            - ZFL_TAFLIGHTS (database table)
            - ZFL_TABOOKS (database table)
            - ZFL_L_CARRIER (data element)
          - ZFL_PLM_UI (subpackage in project)
            - ZFL_PLM_UI_ORDER (program)
            - ZFG_FL_PLM_UI (function group)
            	- ZFM_FL_PLM_UI_PICK_PLANE_POPUP (function module)
    - Problems:
      - Things like ZFI, ZSD, ZMM etc. could not be used either
      - Object names get really long as they need to contain the entire package hierarchy (and the length is very much so limited)
      - Moving objects to other packages is no longer possible (as they would have to be renamed)

  2. Use the layout above but instead of reserving prefixes all abapGit projects have the same prefix and a number (or hash or whatever) after it that is assigned by a central entity
    - Example:
      - ZABG10C7 (project package)
        - ...
    - Problems:
      - You cannot make out at all by the name what the development objects in the package are about
  3. Reserve a namespace for abapgit projects and use the logic above within it
    - /ABGIT/FL_PLM
    - -> even longer names
    - Not sure if installation of reserved namespace development rights is even possible on an unknown number of systems

Not a big fan of any of these.

Solving this problem is in my opinion a requirement for package management / dependency management ( #217 ).

Any thoughts / ideas on this?

**Comment by larshp** [comment]
In the old days of the SAP/ABAP code exchange there were a namespace /CEX/ reserved, however I think it is not used/possible anymore.

Namespaces is the SAP solution to this problem. However, a S user is required to register a namespace, so this is typically not possible for open source projects.

abapGit currently does not enforce any naming scheme for objects, but if an object exists in a different package than expected it shows a warning when trying to overwrite the object.

I have not seen a name-clash yet in the wild ABAP open source world, but hopefully over time we will see more ABAP open source projects, and it might become a problem. If we see a lot of ABAP open source projects, I guess SAP will be forced into having an opinion on name clashes(eg. provide namespaces for OS).

For my projects I typically just prefix the objects with some fixed characters, to reduce the chance of clashes,
Z(CL_)?AOC_ for https://github.com/larshp/abapOpenChecks
Z(CL_)?AGS_ for https://github.com/larshp/abapGitServer

and others also follow this scheme:
Z(CL_)?EXCEL_ for https://github.com/ivanfemia/abap2xlsx

Working with open source projects, then if there is a name clash, I'm sure the community will figure out to rename objects in order to fix the issue.

**Comment by flaiker** [comment]
Thanks for your thoughts. I agree in long term SAP will have to be the one to provide a _clean_ solution for this.

For reference, here are some other projects on this topic:
- [Namespace Exchanger for SAPlink at the Exemplary Example of abap2xlsx](https://blogs.sap.com/2015/08/11/abap2xlsx-namespace-exchanger-for-saplink-at-the-exemplary-example-of-abap2xlsx/)
- [Namespace Refactoring in ABAP](https://blogs.sap.com/2013/03/06/namespace-refactoring-in-abap/)
