### ISSUE TITLE
Branching - Multiple active identical programs

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#382]
Git gets people talking about branching in SAP, from my point of view it is already possible by installing multiple instances, one for each branch.

But what if it was possible to have multiple identical programs installed in the same system?

Idea: rename objects and install side-by-side

Example, main repository contains:
Report ZFOOBAR
Class ZCL_FOOBAR
Database table: ZFOOBAR

Branch and install with different name:
Report ZFOOBAR_BRANCH
Class ZCL_FOOBAR_BRANCH
Database table: ZFOOBAR_BRANCH

this will off cause require changes inside the report + class + database table in order to keep it separated from the original objects. It will not work with dynamic programming and enhancements/user exits, but for isolated reports/custom functionality it should work.

Renaming and adjusting objects will happen automatically via some tool

This is a crazy idea, hence labelled crazy. But with a lot of effort it might be possible to implement.

**Comment by sbcgua** [comment]
imho. adding suffixes to names will not do - name may be too long. Randomly generated names might do (though not quite convenient). 
Offtopic, but what about CI in ABAP ? Let's say there is some online ABAP server (let's say supplied by SAP) programs deploy there with randomly generated names and run unit tests. Alternatively, complete compiler based on abaplint :) The issue is though implementing standard FMs, Classes and etc ...

**Comment by larshp** [comment]
Yea, there will be a problem with too long names, but it can be fixed by storing the mapping of names somewhere. Having randomly generated names will make the programs difficult to maintain, as it is far from the original branch object names.

CI on ABAP: I'm headed in the "complete copiler" direction, with javascript as the target language. But it is quite far out in the future.

**Comment by jrgkraus** [comment]
Not so crazy as it seems. We do something similar. See [blog on SCN](https://blogs.sap.com/2017/03/15/branching-in-abap/comment-page-1/#comment-367023)

**Comment by EduardoCopat** [comment]
Yes, that is an issue. Specially if you want to setup a CI culture as @sbcgua mentioned. 

>But what if it was possible to have multiple identical programs installed in the same system?

I don't think the current NetWeaver architecture supports this, unfortunately. Maybe if the TADIR objects could have different MANDT, thus being not cross-client, it could work.

**Comment by tiefox** [comment]
Sorry to jump in without knowing the inner workings of abapGit yet, but do we need the mulitple programs with the same name at the same time ? 
For instance in a git workspace you only have the source of the current branch available, you need to switch branches and fetch the source changes for another branch from the local repository. Could we do the same, store the other branches in a local repo in the system  and replace the active one when doing the "checkout"  ?

**Comment by sbcgua** [comment]
The problem starts when you want several people to work at the same time. More attention to commit the changes. And of course some stuff that stops working or works differently than you expect for your part.
Even more if it is one file - not possible due to locking and not clear who was ~~daddy~~ author :)
Indeed, unless SAP supports this kind of feature architecturally it looks quite a task if feasible at all.

**Comment by larshp** [comment]
guess I'll close this, no progress, reopen if somebody will work on it
