### ISSUE TITLE
write-protected repo: add lock icon in overview screen

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#386]
https://octicons.github.com/icon/lock/ ?

**Comment by sbcgua** [comment]
I'll have a look

**Comment by sbcgua** [comment]
OK, options

1) instead of repo icon
![image](https://cloud.githubusercontent.com/assets/15635498/19282542/7482b052-8ff7-11e6-95fb-e795232475c3.png)

2) before branch
![image](https://cloud.githubusercontent.com/assets/15635498/19282633/d71ce73c-8ff7-11e6-9e60-130f73c040e9.png)

3) playing with color (d27979)
![image](https://cloud.githubusercontent.com/assets/15635498/19282806/64eaae96-8ff8-11e6-89d5-09f6ebcf9910.png)

![image](https://cloud.githubusercontent.com/assets/15635498/19282850/8c128bce-8ff8-11e6-8e10-6f5a71832d00.png)

Mmmm, I guess 1 or 3.1 ...

**Comment by sbcgua** [comment]
Better to click on image to zoom - in-message is not that clear

**Comment by sbcgua** [comment]
Finetuned icon :) But ... a bit sizy and is not inline with migrating to font plans :(

![image](https://cloud.githubusercontent.com/assets/15635498/19284068/0e1dd9da-8ffd-11e6-87d7-ae17489a0914.png)

**Comment by larshp** [comment]
I like the "before branch", number 2. 

Another follow up issue: move the sync/background mode icon to the same place as the lock icon

**Comment by sbcgua** [comment]
Closing
