### ISSUE TITLE
move background mode icon to same place as write-protected icon

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#388]
after https://github.com/larshp/abapGit/issues/386

**Comment by sbcgua** [comment]
I can have a look.
Not sure that understood "move" :)
Do you mean showing the icon if it has BG job ? Or do you mean removing BG group from the TOC (not sure that it is a good idea, or it should be replaced with some other marker e.g. color coding)

Is there an call to check if the repo has BG task ? Or should I just read repoID from bg_persistence to check it ?

**Comment by larshp** [comment]
Moving it away from the TOC, so the TOC only has online/offline icons

**Comment by sbcgua** [comment]
Mmm, arguable. How do I see the repos with bg enabled from the list ? There should be some other indication. I'll think on it. Maybe color coding or some special symbol somewhere - some kind of superscript "bg" should look fine I guess.

**Comment by larshp** [comment]
well, it is a decision, how do I see the repos with write protection enabled? 

I think we should keep the TOC clean, and then add icons alongside the lock icon to indicate enabled features

**Comment by sbcgua** [comment]
"...I think we should keep the TOC clean...". I agree. I also didn't like that BG line frankly.

**WP and BG indications**: well, they are different imho. WP question raises on the repo level (Can I pull ?), BG question sounds as "Do I have ANY background tasks?" - and this is not answered by UI unless you go through all repos - not good (or maybe I don't understand the pattern of usage - I don't use bg feature honestly ;)

So what I propose: in TOC do it like this

![2016-10-12_12h40_20](https://cloud.githubusercontent.com/assets/15635498/19305943/01c5cd12-907c-11e6-9f83-0bebb867451b.png)

or this (I prefer)

![2016-10-12_12h41_49](https://cloud.githubusercontent.com/assets/15635498/19305949/04c84102-907c-11e6-80fe-f3795bbc2eb4.png)

In repo as you suggested. But I'd suggest letters (below) because icon is not clear - it is for refresh more than for bg job (or another one should be used, this icon is just not good for bg)

![2016-10-12_12h39_25](https://cloud.githubusercontent.com/assets/15635498/19305968/1ae4125e-907c-11e6-8429-53dd299f9b20.png)
 
The style is not final - I'll finetune later, but the general idea should be clear.

**Comment by larshp** [comment]
above looks good to me

**Comment by sbcgua** [comment]
Closing.
There is some space for unification (visual) of these attributes. Maybe will spend some time on that later
