### ISSUE TITLE
code review with gerrit / push to refs/for/master

### ISSUE THREAD

**Issue by stotz89** [larshp/abapGit#415]
Hi,

Is there a possibility to push content to gerrit code review? I was debugging a little bit and changed some values (especially the branch name from refs/heads/master into refs/for/master) during the runtime but the https-response sends me back an error that says: 'unpack ok - no such ref'. 

In fact I the program right now wants to push directly to the head branch refs/heads/master. When I do that the https-response says that this is prohibited by gerrit. 

Is there a solution or a PoC?

Thanks in advance.

**Comment by larshp** [comment]
Hi,
abapGit uses the raw git protocol for communicating with a git server over https, so I'm pretty sure this is something we can get working.

I'm not very familiar with Gerrit, but loking at http://wiki.qt.io/Gerrit_Introduction it seems like the client has to create the branch? The "Branch" menu can be used to create or switch between branches:

![image](https://cloud.githubusercontent.com/assets/5888506/20182154/259b6566-a761-11e6-9a15-691ad779572f.png)

**Comment by larshp** [comment]
I've got https://hub.docker.com/r/fabric8/gerrit/ running, but it turns out that Gerrit, by default, uses digest authentication for git over http(https://git.eclipse.org/r/Documentation/config-gerrit.html).

For more information see:
https://en.wikipedia.org/wiki/Digest_access_authentication
https://tools.ietf.org/html/rfc2069
https://tools.ietf.org/html/rfc2617

First step will be to build the digest authentication, for this purpose I've created repository https://github.com/larshp/abapDigest

In your(@stotz89) example above I guess the default Gerrit setting has been modified, after fixing the authentication we'll get to the refspec issue.

(Digest looks easier than NTLM, https://github.com/larshp/abapNTLM)

**Comment by stotz89** [comment]
Thank you for effort here. 
I have now figured out that gerrit offers some REST APIs: https://gerrit-review.googlesource.com/Documentation/rest-api.html

Using this will work fine hopefully :).

**Comment by larshp** [comment]
Hi,
I've implemented the digest authentication in https://github.com/larshp/abapGit/pull/428

And successfully pushed code to the master branch of the git repository hosted on Gerrit. Next step is to look into the refspes so changes can be pushed to refs/for/master to tigger a review

I think the REST api is only for eg. user management, and not for versioning and pushing code

**Comment by larshp** [comment]
I did some manual changes in the code, and successfully submitted a change/review from abapGit to Gerrit :tada: 

![image](https://cloud.githubusercontent.com/assets/5888506/20317558/cd27f1e2-ab66-11e6-8a7d-a29ddb7beea9.png)

I need to read a bit up on the Gerrit flow, and then we'll have to do a few tweaks and add a few features in the abapGit user interface.

**Comment by larshp** [comment]
there is still some work in this, however I dont have access to a Gerrit server anymore 😢

**Comment by larshp** [comment]
please open a new issue if this is still relevant, I guess now 3 years later most are using the features of the git server to do reviews
