### ISSUE TITLE
separate logic and UI in ZABAPGIT_VIEW_REPO

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#424]
eg METHOD get_remote + METHOD list

**Comment by sbcgua** [comment]
Mmm. Do you mean split it to different includes ?
Regarding the code comment - I agree, I'd rename `get_local/remote` to `get_on/offline_repo_items`. `get_local` though cannot be moved to `lcl_repo` - it fills `ty_repo_item` structure - which is UI related, not internal logic. I would keep it there. Maybe (???) it can be based on `get_files_local` instead of `get_tadir` - files are cached and etc - but offline repos do not show files, so I'm not sure if it is really good idea (what do you think ?).

**Comment by larshp** [comment]
I think first step is to move the code that is not directly view, but logic to a new include, then it will be easier to rename

**Comment by sbcgua** [comment]
ok, adjusted. Renamed methods but didn't adjust get_tadir.

P.S. will PR a bit later together with some other fixes

**Comment by sbcgua** [comment]
Closing
