### ISSUE TITLE
Favorites - Initial setup

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#454]
An idea, if the user does not have any favorites, can we present the list of repositories and possibility to select favorites, instead of showing a random repository in the green field:

![image](https://cloud.githubusercontent.com/assets/5888506/20531750/ffd52a08-b0d7-11e6-93cc-096833240bd2.png)

**Comment by larshp** [comment]
and perhaps use the same space for the tutorial/description on how to add favorites

**Comment by sbcgua** [comment]
I'd say that if there are no favs and no 'show_repo_id', then it would mean that the user is completely new and maybe show him something. But missing favs alone is not enough to trigger imho. Maybe I don't care about favs and choose them from complete list.
Tutorials is a good idea. I was also thinking to embed some documentation into UI. But no concrete solution. I was thinking about some kind of downloading it from Wiki (assuming github is accessible) so that there are no or almost no text in-code, but some external help-ids.

**Comment by larshp** [comment]
ok, lets see how it works out
