### ISSUE TITLE
Top menu

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#487]
The top menu is getting quite crowded,

![image](https://cloud.githubusercontent.com/assets/5888506/20866090/e7648874-ba23-11e6-8481-19b6d5f0d2c2.png)

Few thoughts:

a: Move "Clone" and "New offline repo" to a dropdown "New" where online or offline repo can be created

b: Move "Get abapGit" to "Advanced" dropdown, and split it up in 2, one for abapGit itself and one for plugins

Any comments/other ideas/opinions?

**Comment by sbcgua** [comment]
Mockup (2 variants):

![image](https://cloud.githubusercontent.com/assets/15635498/20866346/31482fee-ba34-11e6-9a51-386fb64b9f6f.png)

a) Imho crowdness is because of heavy "New offline repo" label. I wouldn't put clone/new to a droplist - these are quite major and used commands. I'd leave them on the first level.

b) I think I mentioned that somewhere already but I don't understand the idea of this "Get abapGit" command. E.g I have it although it is installed (that's because it checks repo URL and put my fork there). If I understand correct this is purely for new users who just installed AG as a one file prog. So ... I'd better put the links to tutorial, along with some better explanations, plugins and etc. Or (even better strategically) to Explore page. Or to both.

**Comment by larshp** [comment]
a: 👍 LGTM

b: yes, it is for new users, it makes it a bit easier to install from the git repository. I like the idea with moving it to the explore page

**Comment by sbcgua** [comment]
OK, so ...

a) keeping the first option ? (I can do, but prob tomorrow)

b) I can add some info to tutorial (including links) and remove from main menu. Explore page is on you then. 

P.S. Is it already safe to push commits ? :)

**Comment by larshp** [comment]
commits safe: yes, it always is, I'm just trying to avoid conflicts with pull requests that are in progress. So try not to change any of the files that are part of open pull requests

**Comment by sbcgua** [comment]
WIP:

![image](https://cloud.githubusercontent.com/assets/15635498/20896766/ea27a8de-bb27-11e6-9779-b87de446b304.png)

But I think I'll redo the install handling. It will check if abapGit installed right before cloning and show a message if so. And probably will check not only repourl but that the program ZABAPGIT exists.

**Comment by larshp** [comment]
cool

"AbapGit repositories" -> "abapGit repositories"

and I guess it could be nice if the add online/offline is moved to a section for itself, with a bit more explaining on the difference between online and offline

**Comment by sbcgua** [comment]
@larshp 
Almost finished. One question: I wonder how to detect if AG is installed. (and plugins). https://github.com/sbcgua/abapGit/commit/cbcdb3e8fc506c957417b88e664332b66218ba4d#diff-7c86cd1940d276a2448b6a072e54e932R145

Why: Now it is checking repo url (which is almost ideal actually). But: I have both installed. But AG is linked to my repo so it is not found as installed. I thought to check the program name, but actually I can install fulltext abapGit to zabapgit - so not an option. Thoughts:

1) check some other includes. Which would be the most typical ??
2) make abapmerge to put some static marker (variable). Cool, but looks like an overkill. 
3) analyse actual fork urls at github (?!?! crazy)
4) Don't care. Actually since it is not in the top menu anymore and not annoying, maybe it is not that bad. Although may be confusing for contributors. 
5) More ideas ?

**Comment by larshp** [comment]
closing
