### ISSUE TITLE
Large package takes too long to load

### ISSUE THREAD

**Issue by christian1020-94** [larshp/abapGit#537]
I configured an offline repository for the main development package in the client (~25k objects). It's taking too long to load. Is there a way to bypass this? I saw the user config to filter only changes, but as is the first time I'm setting the package, there are no changes at all, so it tries to load every object.

    METHOD filter_changes.

      DATA lt_repo_temp LIKE ct_repo_items.

      FIELD-SYMBOLS <item> LIKE LINE OF ct_repo_items.

      LOOP AT ct_repo_items ASSIGNING <item>.
        CHECK <item>-changes > 0.
        APPEND <item> TO lt_repo_temp.
      ENDLOOP.

      IF lines( lt_repo_temp ) > 0. " Prevent showing empty package if no changes, show all
       ct_repo_items = lt_repo_temp.
      ENDIF.

    ENDMETHOD. "filter_changes

**Comment by larshp** [comment]
25k objects, wow, I havent had a chance to test with this many objects. How long does it take, more than half an hour or does it dump due to timeout?

"filter changes" only affects what is shown to the user, not the serialization.

What type of objects are the most common in your package? Thinking of writing a utility program to generate eg. 20.000 objects automatically, so we can look into what can be done

**Comment by christian1020-94** [comment]
Mmmm haven't had the chance to let it finish, in some hours at work I will measure it. 
About the most used objects, well it's a package used for development in general (I think 90+% development is done there). From the statistics, programs, data elements, tables and transactions are the most common, but as I said, almost every development is done in this package.

**Comment by VishnAndr** [comment]
Parallel execution of serialization might reduce the time?

**Comment by larshp** [comment]
Parallel: yeah, but it is difficult to distribute RFC function modules in an easy installable report. Think it might be easier to avoid SELECT SINGLE and still get some better performance in some places, however it looks like this issue is related to the HTML rendering.

@christian1020-94 try again with latest version

I have changed the code so it only renders the first 500 objects in the object list. This should avoid long runtime for very large projects, and all functionality should still work.

Used https://github.com/larshp/ABAP_Mass to test, created 2000 domains and experienced the problem with HTML.

**Comment by larshp** [comment]
cool 😄

**Comment by christian-94** [comment]
@larshp about the "only first 500 objects shown", could this number be configured via user config XML? Is it possible?

**Comment by larshp** [comment]
yeah, feel free to implement this as a setting under Advanced -> Settings. If you find the page, then I guess there is a a few examples on how to add data to the persistency

**Comment by sbcgua** [comment]
a comment: but why html renders slowly ? If it is AG problem, I might have a look, maybe something to do to improve performance. 

Besides: I think user setting **is not** the best option. Let's assume performance cannot be improved. Then the page is not informative now - it just cuts the list which is not clear for user: I'd add some footer to the end which informs about the situation and gives some buttons to chow more data right at place. 

Let me have a look on this (most probably this weekend I"ll check)

**Comment by christian-94** [comment]
@sbcgua Mmmm but then there won't be option to even cut the list more? For example, I'm working in a ~25k objects package and when making some tests, with 500 objects shown it longs for ~30 seconds I think, which gets annoying when doing multiple tests.

**Comment by larshp** [comment]
why html renders slowly: too many loops in the ABAP when handling the HTML, perhaps it can be improved, however I think it will still be a problem with ~25k object packages if everything is rendered

there is a message at the end of the list informing the user that the list has been cut, https://github.com/larshp/abapGit/blob/master/src/zabapgit_view_repo.prog.abap#L174

**Comment by sbcgua** [comment]
@christian-94 _"but then there won't be option to even cut the list more?"_: yeap, makes sense. You're right. let's make the option too and I'll have a look to performance and UX in the meanwhile

@larshp didn't see that line, sorry :) I'll check the performance. If unsuccesfully, I'll add some usability stuff there.

**Comment by christian-94** [comment]
@sbcgua can I work on adding the option? It's not too complicated so I can practice my interaction with Github too...

**Comment by sbcgua** [comment]
@christian-94 sure :) I actually didn't mean to take it completely :) I'm just a bit obsessed with UX so I stepped in 😄

**Comment by christian-94** [comment]
@larshp @sbcgua Mmm, then this option will be an input field in the Advanced > Settings page? Or will it be another tag in the user config XML?

In other words: lcl_settings or lcl_persistence_user?

**Comment by larshp** [comment]
Just make it global, I think the other settings in the Advanced -> Settings page is global

i.e. `lcl_settings`

**Comment by sbcgua** [comment]
Looking into performance. Some stats for 2000 domains (top time consumers):

![image](https://cloud.githubusercontent.com/assets/15635498/22181892/0c7fe35a-e09f-11e6-97e6-aea9c8281f96.png)

Most probably the issue is that lcl_html rebuilds string on every addition. I'll try to move it to some `render`. `mv_html` will thus become private. And many small patches to the remaining code which uses `mv_html` directly.
 in progress ...

**Comment by sbcgua** [comment]
Some improvements are coming ;)

![image](https://cloud.githubusercontent.com/assets/15635498/22183719/b260ff16-e0cc-11e6-9d12-985677d6ef9a.png)

(time in sec, 2000 iterations of some patch of html)

**Comment by sbcgua** [comment]
Yohoho ... seems like the rating has shuffled a bit :)
![image](https://cloud.githubusercontent.com/assets/15635498/22183810/413a6a90-e0cf-11e6-868e-94037c0065ed.png)

**Comment by sbcgua** [comment]
@christian1020-94 After PR that would be interesting to test on your huge package without limitation :) For 20k object I think it will be still 'under acceptable level' but just interesting what is the factor of improvement. Would appreaciate if you'll check :)

P.S. pls don't close yet I'd like to have a look on that bottom button UX yet (somewhen during the week).

**Comment by christian1020-94** [comment]
@sbcgua Wow! It took less than 1 minute to load all the ~25k objects :smile_cat: Great work.

**Comment by sbcgua** [comment]
Cool ! I didn't expect so big impact !
Yeah, make it work, make it proper, make it fast ... :)
Thanks for the test and for the interesting issue to solve :) 👍

**Comment by larshp** [comment]
close issue and move the "bottom button UX" to new issue? It will give a better overview, as this issue contains 30 comments

**Comment by christian1020-94** [comment]
Yes, I guess it's better. Closing this issue then. @sbcgua will create the "bottom button UX" issue I think.

**Comment by sbcgua** [comment]
Ok, i'll create
