### ISSUE TITLE
local dot abapgit state, follow up

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#652]
from https://github.com/larshp/abapGit/pull/649

**Another issue: If I change DB page** the local .abapgit is not reloaded (even after repo refreash). This is a separate issue though - it is more to post-handling of DB changes than to local .abapgit feature itself.

**Another one: if I zip the package** I have as repo then just default .abapgit is saved. Not the one from repository. Not sure it is a bug itself. But maybe some place for process/UX improvement. Maybe `package to zip` should  check if this package has repo or maybe a repo advance commands has to have own save to zip ... probably a separate issue too.

**Comment by erdenber** [comment]
Hi Lars,

not sure if this is related to this issue or a separate one: I tried to change an offline Repo to FULL folder logic. The problem is that during rendering a default dot abapgit is created for offline repos instead of using the one from the DB. This happens in 
LCL_REPO_CONTENT_BROWSER->BUILD_REPO_ITEMS_OFFLINE() and subsequently reaches PACKAGE_TO_PATH() where the "Unexpected package naming" error is thrown. 
Sorry if this is unrelated to #652 - if it is I will happily create a separate issue. 
Cheers, Thomas

**Comment by larshp** [comment]
@erdenber please create it as a separate issue, then we can try to solve it in there

**Comment by larshp** [comment]
closing

db: not really an issue, as we now have the gui for editing

zip: I think this is solved
