### ISSUE TITLE
Create a repo with multiple packages

### ISSUE THREAD

**Issue by giovannidegani** [larshp/abapGit#681]
In some use cases that I have, I would need to create a repo that has objects from different packages, would be useful to be able to create a repo offline specifying one or more packages and then set a remote to push the objects to it, later one being able to add more objects from other packages into it.

**Comment by larshp** [comment]
just put everything in one repository?

you can have one superpackage and add subpackages to it when needed

**Comment by tiefox** [comment]
I know we discussed about the superpackage, but this would not work for changes in SAP standard that would need to be tracked and code reviewed.

**Comment by tiefox** [comment]
My plan to tackle this is this:

- Modify the repo xml file to accept multiple packages
```xml
<?xml version="1.0" encoding="utf-16"?>
<asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
 <asx:values>
  <REPO>
   <URL>https://lego-cit-ux-solutions.visualstudio.com/ODataBase/_git/YCA-ODATA-BASE</URL>
   <BRANCH_NAME>refs/heads/NPLK900032</BRANCH_NAME>
   <SHA1>dc36052aa0865ed46b93ffaf8a7d1f1c1353983d</SHA1>
   <PACKAGES>
     <PACKAGE>YCA-ODATA-BASE</PACKAGE>
     <PACKAGE>Z_MY_PACKAGE</PACKAGE>
   </PACKAGES
```

-  Make a Database migration step
- Modify all parts of the code that will be impacted by this  :(
- Add in the + offline  menu option to select multiple packages
- Addi in the repo advance menu an option to add a new package to the repo

**Comment by larshp** [comment]
Hi,
I am very much in doubt if this is needed.

A: in the above example create a superpackage ZSUPER with subpackages YCA-ODATA-BASE and Z_MY_PACKAGE and it will work with the current version of abapGit.
The structure of your system will be reflected in SAP and and the same in git, ie. the connection is transparent for developers in both systems.
One to one relations are easy, many to many are difficult, so introducing multiple packages will have a wide effect on the abapGit code complexity.

B: with packages YCA-ODATA-BASE and Z_MY_PACKAGE in one repo, would all files go to the same directory in git?
Or alternatively the ZSUPER package would have to be simulated in the code to get the correct structure.

As I understand, the problem you are trying to solve is getting SAP standard modifications into a branch so it can be reviewed with TFS or GitHub.
Eg. you have a modification/repair in SAPMV45A and if there are changes in the include, it should go into the branch to be reviewed.

1: Since SAPMV45A is part of package VA, would package VA then be added to the repository? There are ~6700 objects in the VA package.
I'm afraid that suddenly most SAP standard packages would then have to be stored in git? As packages have to be included if one object has one repair.

2: Another approach: move all your custom code out of the SAP namespace as soon as possible. Use implicit enhancements instead, or call
a class as soon as possible from the repair. Then the code changes would be part of customer namespace.
It will also help you when moving to eg HANA on ECC, as it is only possible to scan custom code for problems(SAP objects are not scanned).
And repairs would be smaller resulting in faster upgrade/SPAU process.

3: Another approach: list all objects that are not part of the package/repository as a message in the commit/PR. Then during 
review; the reviewer would manually have to look up the object in the system and review it there.
This will be the same case as for all the object types that are not currently supported https://github.com/larshp/abapGit/wiki/Supported-object-types

4: Another approach: add the reparied object in the branch, ie. objects that are not part of the package/repo are added in full. 
Some code bits would have to be changed, but my guess is that this will be quite easy.
Downside is that the object will appear as added.

4a: addition to 4, add the previous version(looking the SAP version) of the object to the master branch, and the latest to the transport branch.
This will make sure the diff is correct.

**Comment by tiefox** [comment]
Thanks for the extensive comment.

I have been thinking about this "requirement" and for a moment lets forget about the tracking of SAP standard object changes for review purposes.

For me the main case for this is lowering the barrier for entry for organizations that haven't been so good in maintaining a proper organized package structure. Ask them to revamp this before going to abapGit might be a deal breaker, not sure.

For point B:
When creating a new REPO, the default behaviour would be to put objects into folders named after each package.
An existing repo would remain the same, if someone adds a new package to it, it goes into its own folder.

It also about flexibility in defining how you want you repo and be able to build it the way you want to.
I agree that will add some extra complexity in the code, but I dont think it is not that much and "unmanageable".

Back to SAP standard code changes handling.

Tracking whole SAP packages in the repo is definitely not good so the best approach for those would probably be your 4 + 4a.

**Comment by larshp** [comment]
_Revamp_: typically I have seen organizations not using packages at all, eg putting everything into Z001 package, in this case there is no problem. 
Another typical approach is having ZMM, ZSD, ZQM ... packages, in this case a Z superpackage can be added, this is(from my point of view) a very small change. Unless there is a lot of packages, and if there are a lot of packages then a proper package structure should be made anyhow.

I think having a 1:1 relation between what can be seen in SE80 and the git repository, will make it more transparent for developers/users how it works.

**Comment by larshp** [comment]
Guess this can be simulated by adding some code in the following user exit,
https://user-images.githubusercontent.com/5888506/44190546-99be9280-a127-11e8-9a07-c902c537e210.png

**Comment by larshp** [comment]
not in scope, can be accomplished via the user exit, closing
