### ISSUE TITLE
JS init error

### ISSUE THREAD

**Issue by larshp** [larshp/abapGit#782]
@sbcgua any tips for debugging a "JS init error" ?

![image](https://user-images.githubusercontent.com/5888506/27009798-5de28d0e-4e97-11e7-8ab3-6f0e8f4d6389.png)

**Comment by sbcgua** [comment]
I copy html into a file (right click -> view source), save js and css in nearby JS and CSS folders (manually or with this - https://github.com/sbcgua/abap_w3mi_poller) and run it is Explorer/Chrome (where I can see console and easily modify js for debug msgs).

Or there is `debugOutput` js function which prints stuff in bottom right corner when you run AG. But this appeared to be less convenient than it was planned. :)

Is it just for this repo ? The first though is that it is because the stage table is empty. How did you call a page with empty stage ?

P.S. sorry for some silence from my side - a lot of work currently. Might have some more time in July.

**Comment by larshp** [comment]
Thanks, I lost the example, so I'll close the issue, but now the information is here if it happens in the future. It might be caused by one of the other bugs I fixed earlier today.

P.S. no problem, important things first
