### ISSUE TITLE
CMPT - Code Composer Template Serialization

### ISSUE THREAD

**Issue by christianguenter2** [larshp/abapGit#888]
Recently I stumbled over an interesting blog about Code Composer.
https://blogs.sap.com/2015/09/11/step-by-step-to-generate-abap-code-automatically-using-code-composer/

Additionaly I detected that there's also a repository object called Code Composer Template.
![image](https://user-images.githubusercontent.com/17437789/29088122-79d2634a-7c78-11e7-8f6e-38a02f20717c.png)

![image](https://user-images.githubusercontent.com/17437789/29088408-4423bf5e-7c79-11e7-9af8-a5266fb01382.png)

Why not support it within abapGit?

**Comment by flaiker** [comment]
I was very surprised when I found them some time ago (also triggered by the same blog I think). Generating WebDynpro classes (controllers I think) seem to be the main usage. Though what I found so far it is always a standard INCLUDE with the template in it and not the dedicated repository object. There's even support for parsing commented out lines within methods as templates. I assume because the template syntax was a syntax error at some point.

The documentation for it unfortunately seems to be very much SAP internal, so I haven't really bothered to analyze enough of the API to see if it would make sense to use for any projects.

Do you have any experience with it?

**Comment by christianguenter2** [comment]
No, unfortunately no experience at all. Just had some fun exploring the APIs ;-)
