### ISSUE TITLE
Downloading files to a local git repo and keeping sync

### ISSUE THREAD

**Issue by fareez-ahamed** [larshp/abapGit#93]
As you have options to upload to different git services, is it possible to download the files to a local git version controlled folder. And the ability to sync to that folder whenever we make update in the system?

BTW Quite impressed with your work :smiley: :+1:

**Comment by larshp** [comment]
no, the distributed part of git is not implemented. However I recently implemented offline projects, this allows you to download the files as a zip archive, the contents of the zip file can then be moved to a local git folder and synced if needed. Though, its a lot easier to make sure that the SAP system is in sync with the repository for an online project.

Also wondering if branches can help you out, make a branch of of the git repository, commit your changes to the branch/fork, and merge it to main branch when needed or development is done.

**Comment by fareez-ahamed** [comment]
I'll not be able to use it for client projects where git is not the workflow and we would not be having access. I wish to have a version controlled local repo so that I can sync to it, go back to previous versions, switch branches if needed..

**Comment by larshp** [comment]
hmm, I've mainly been thinking of sharing ABAP code via git, the offline project option I see very useful for installing code, not so useful for committing into git.

As I understand it, you will not be able to connect to a git repository on the internet, so one possibility is to setup a git server within the network(gitlab enterprise edition is free), however this might also be difficult to setup at clients.

If going for a local repository solution, with a project with multiple developers, something needs to be setup for sharing the local files among developers, or alternatively one central person would do the git commits, this would serve more of a backup solution than a collaboration tool.The backup setup can be handled via offline projects.

There is also version management built into SAP, however if you have a large project, it will be nice to make a snapshot(commit) of all the objects at one point in time, instead of having to manually go through all objects.

I've also been thinking of implementing a git server in ABAP(as a SICF service), but its kind of a crazy idea. :stuck_out_tongue:

**Comment by larshp** [comment]
hi, I've added a project for a git server, https://github.com/larshp/abapGitServer

Can it be used to solve your issue? There is no ETA on the server, however feel free to contribute.

**Comment by fareez-ahamed** [comment]
Hi... But I donno how much SAP as a git server will solve my problem... Maybe I'll be able to clone a repo and pull things out of it... Will it support push as well..?

I was thinking about a more simple solution for my case. I wanted to take the serializers from your agapGit and make it save it to local location and make a git commit to the local folder automatically...

I really think serializers should be common, that we can use it in many different projects for many different purposes, And we can add more object types to it... :smiley:

**Comment by larshp** [comment]
git server: clone, pull, push -> yes

simple solution: yea, that could be a nice feature for offline projects, could add another link next to "Export zip" and "Import zip", perhaps "Export to filesystem and commit". It would need to know the folder to export the files to, and perhaps where the git executable is located if it is not part of PATH, and a small popup for the commit message.

serializers: one of the design goals for abapGit is to keep the installation easy, so I'd not like to move it to separate classes, we could add some FORMs to be called from external programs if needed. Feel free to take the serializes and use in other projects as stated in the LICENSE. You can still add more types to abapGit just edit the file and make a pull request :wink:

**Comment by fareez-ahamed** [comment]
Sure... Thanks..! :smiley:

**Comment by larshp** [comment]
hi, see the above commit, it now lets you export the files to a folder for offline projects.

there are still some things missing, see todos in the code

![image](https://cloud.githubusercontent.com/assets/5888506/8527124/2aa8aeae-240b-11e5-9dec-3ed511cf321b.png)

**Comment by larshp** [comment]
Hi Fareez,
I did the last changes, take a look, can this issue be closed?

**Comment by larshp** [comment]
HI Fareez,
I'm closing this issue, please create a new issue if you have any comments
