### ISSUE TITLE
abapGit on SAP JAVA Gui via Eclipse(ADT) not working

### ISSUE THREAD

**Issue by Sdfraga** [larshp/abapGit#930]
I am using SAP JAVA Gui on a Mac and I am moving more and more to Eclipse IDE. Unfortunately, the abapGit program does not render the HTML when executed via Eclipse.

<img width="1680" alt="abapgit on eclipse with sap java gui" src="https://user-images.githubusercontent.com/16186872/30770847-dbd4e154-a03a-11e7-9966-a578351495c7.png">

If I execute abapGit via SAP Logon it works perfectly.

I already saw issue #110 and the demo programs are working fine in Eclipse. 

My environment is:

Eclipse Version: Oxygen
SAP Version: 751
SAP GUI for Java 7.40
(Version ID 074000040000)
Java VM: Oracle Corporation Version 1.8.0_131
OS: Mac OS X(x86_64) Version 10.12.6

**Comment by pokrakam** [comment]
Never had any html in JavaGUI problems on my system over various versions. Currently using Neon, but that shouldn't make a difference because we're already inside the JavaGUI by the time we reach the HTML layer. I wonder if Java might be the issue? Does it work if you run JavaGUI standalone?

$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

SAP GUI for Java 7.40 rev 9
macOS 10.12.6

Currently on a mobile connection but if I find some time and bandwidth tomorrow I'll see if I can download Oxygen

**Comment by Sdfraga** [comment]
If I execute abapGit in Java Gui standalone I don't have any issue, it's only if I execute abapGit in a GUI session inside Eclipse.

Can you execute abapGit in your Eclipse Neon?

I have tried to execute abapGit in Eclipse Mars which is also installed on my machine and the result is the same. Blanck page with only the program title just like the printscreen in my first post.

My Java version:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by pokrakam** [comment]
Yes it works fine on Neon. I don't have my Mars ADT instance anymore so can't test that, but have used it on a Mac since Luna and never had any issues with missing html.
My Java is a bit outdated, so will also update that tomorrow. If it stops working on my system I'll blame you :) 
Note that you may have several versions of Java installed. From the command line, try: 
`$ whereis java`
to see which one will be executed by default. It should be `/usr/bin/java`
It's quite possible your browser will use a different Java runtime to a standalone java app, which can be a different version. 
The browser Java runtime lives in 
`/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/` on my system. This is also the one that gets updated via the system preferences or Java website. The other one needs manual updating.

**Comment by Sdfraga** [comment]
Regarding Java I only have one version and it's located on /usr/bin/java like you mention.

<img width="391" alt="screen shot 2017-09-26 at 10 29 52" src="https://user-images.githubusercontent.com/16186872/30850541-19c031a4-a2a6-11e7-82b5-807737c22b14.png">

So at this stage everything points to the Java version..
I will wait for your feedback after you upgrade to Java 1.8. 

Thanks for your help :)

**Comment by pokrakam** [comment]
I was already on 1.8, over patch level. But I have now updated to the latest patch level 1.8.0_144, and it still works. 
Upgraded Java GUI to 7.5 and it still works.
All in all I have a completely new environment - New Eclipse, new Java, new GUI, and it all works. 
An offbeat suggestion, maybe there's a protocol issue, try briefly disabling the firewall and running it while it's off.

**Comment by Sdfraga** [comment]
What a mystery...
I don't have any firewall configured so it's not that.
I will try to upgrade the Gui to 750 like you did since I am getting out of options...

**Comment by pokrakam** [comment]
It's part of the OS: _System preferences > Security > Firewall_

**Comment by Sdfraga** [comment]
The problem is finally solved.
I have installed the latest Java Gui 7.5 and it now renders the HTML inside ADT.

Thanks @pokrakam for your help.
