### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by EduardoCopat** [larshp/abapGit#990]
According to Github [community standards](https://github.com/larshp/abapGit/community), we should have a template for a new issue.

What information could be present? An idea:

### NetWeaver version

**Comment by larshp** [comment]
yeah, but what should it contain? And as of now, I think people are pretty good at creating issues

**Comment by flaiker** [comment]
Some ideas:

### Description
[Describe the issue here]

### Steps to reproduce
[if it is an error]

### System environment
- abapGit version number: [see `zif_abapgit_definitions=>gc_abap_version` or latest master]
- Installation type:
  - [ ] Using the copy paste report
  - [ ] As a repository
- AS ABAP version: [see `System -> Status -> SAP System data -> Component -> SAP_BASIS`]


Though I agree, quality of issue reports seems to be quite high anyways.

**Comment by EduardoCopat** [comment]
Yes, people are creating good issues, but this template may help, even though it adds bureaucracy.

@flaiker That looks great. Some additions, because people sometimes ask questions (instead of reporting problems)

### Description
[Describe the issue or question here]

### Steps to reproduce
[if it is an error]

### System environment
- abapGit version number: [see `zif_abapgit_definitions=>gc_abap_version` or latest master]
- Installation type:
  - [ ] Using the copy paste report
  - [ ] As a repository
- AS ABAP version: [see `System -> Status -> SAP System data -> Component -> SAP_BASIS`]
